apache/pulsar-site

.asf.yaml

Motivation
We are ready to switch over website publishing to the pulsar-site repository.
Modifications
Update the .asf.yaml file which to publish the website from the asf-site-next branch.

[PIP-87][Website] Publish website from asf-site-next branch

---

site2/website-next/docs/reference-rest-api-overview.md
site2/website-next/sidebars.json

As discussed, the drop-down menu for REST APIs will be removed in the new Pulsar doc site.
Alternatively, we need a topic to provide an overview and links to each category of Pulsar REST APIs.
1. Add a new `reference-rest-api-overview.md` file with an overview and links to each category of Pulsar REST APIs.
2. Modify the `sidebar.json` file to add the ID `reference-rest-api-overview`.

[doc] add new file for Pulsar REST API

---

site2/website-next/src/pages/ecosystem.js

[improve][website] Add license explanations to Ecosystem page

---

site2/website-next/src/css/custom.css

Complete five（Show GitHub Star NO） from https://github.com/apache/pulsar/issues/15550

fix no stars

---

site2/website-next/brodocs/pulsar-admin-manifest.json

Currently, the `bin/pulsar-admin bookies` documentation is not on the website. See here: https://pulsar.apache.org/tools/pulsar-admin/2.10.0-SNAPSHOT/ and https://pulsar.apache.org/tools/pulsar-admin/2.11.0-SNAPSHOT/.
I think the issue is likely a missing entry in the modified manifest file. I generated the code for this PR by running the following:
```bash
cp -r site2/website/brodocs/ site2/website-next/brodocs/
```

Add bookies command to pulsar-admin cli documentation page

---

site2/website-next/src/css/custom.css

In #75, `display: list-item` and `counter-reset` are used to add line number in code blocks, which impacts the index of normal `<ol>` elements. This PR uses `display: inline-block` and a number of styles instead and should fix apache/pulsar#15662.

Fix wrong step number caused by #75

---

site2/website-next/src/pages/contributing.md

[feat][workflow] add links of doc contribution guides to Pulsar contribution page

---

site2/website-next/scripts/replace.js

Fixes https://github.com/apache/pulsar/issues/15984.
We have many versioned links in our docs. We replace those links by running `node replace.js` on the script I update in this PR. The versioning is currently broken.
* Fix the `clientVersionUrl` method in the `website-next/scripts/replace.js` file. Note that this changes the method so that it matches the `website/scripts/replace.js`.

Fix versioned links for clients

---

site2/website-next/scripts/replace.js

In #124, I incorrectly included a trailing slash, which led to URLS getting generated with `//` at the end. This PR fixes that mistake.

Remove trailing slash from clientVersionUrl

---

site2/website-next/docusaurus.config.js

fixes- https://github.com/apache/pulsar/issues/14928.
Now the rest-api website url is: 
https://pulsar.apache.org/admin-rest-api/?version=@pulsar:version_number@&apiversion=v2#operation/healthcheck
But we generate the url is: 
https://pulsar.apache.org/admin-rest-api#operation/getActiveBrokers?version=@pulsar:version_number@&apiVersion=v2
We should generate the link to match rest api url.

Fix the doc link mismatch problem.

---

site2/website-next/docusaurus.config.js

We need to make clear that Pulsar is a trademark of the ASF.

Fix Website Trademark Attribution

---

site2/website-next/src/pages/index.js

We should properly attribute the trademarks for Apache® Pulsar™ on first use

Use ® and ™ on first use of Apache and Pulsar

---

site2/website-next/src/css/custom.css

Something's different between local `yarn start` site and published site and I haven't figured out why. Hopefully this temporary fix will resolve the style error in tab highlighting.

Fix tab highlighting error

---

site2/website-next/scripts/replace.js

In https://github.com/apache/pulsar-site/pull/138, I forgot to add the `(` to the replaced string. Without the right paren, the links were rendering incorrectly on the website. This PR fixes those links.

Fix replace script for clientVersionUrls

---

site2/website-next/data/resources.js

Add a blog to the Pulsar website. Two engineers from Tencent contributed it to the community. It talks about optimization and troubleshooting tips for managing large Pulsar clusters.
Preview image:

[BLOG] Add a blog to the website

---

site2/tools/api/python/generate-python-client-docs.sh

Put generated python docs into the `website-next` directory, as @tisonkun explains in this comment https://github.com/apache/pulsar-site/pull/182#issuecomment-1230199254.

Make generated python docs go to website-next directory

---

site2/website-next/src/components/CommonTable.js
site2/website-next/src/components/ConnectorTable.js
site2/website-next/src/components/GuideTable.js
site2/website-next/src/components/MailTable.js
site2/website-next/src/components/OldReleaseTable.js
site2/website-next/src/components/ReleaseTable.js
site2/website-next/src/components/TeamTable.js
site2/website-next/src/components/VersionsTable.js
site2/website-next/src/css/custom.css

Fix #173 
Two style improvements:
**1. Improve dark mode table view:**
Original:
Improved:
**2. Improve light mode table view:**
Original:
Improved:
BTW, this PR reverts some changes of #181. Because PR 181 fixes some font styles, I revert them to make style self-adaption.

style: improve table css style

---

.github/workflows/ci-pulsar-website-next-build.yaml
site2/tools/build-site.sh
site2/tools/pulsar-admin-doc-gen.sh
site2/tools/pulsar-client-doc-gen.sh
site2/tools/pulsar-config-doc-gen.sh
site2/tools/pulsar-doc-gen.sh
site2/tools/pulsar-perf-doc-gen.sh

Add double quote to shell variables and add `VERSION` env variable to `build-site.sh`.

Improve doc gen scripts

---

site2/website-next/scripts/code.json
site2/website-next/scripts/split-version-build.sh
site2/website-next/src/css/custom.css
site2/website-next/src/theme/DocVersionBanner/index.js

fix docs banner text

---

.asf.yaml
README.md

This is proposed by @Anonymitaet at https://github.com/apache/pulsar-site/issues/173#issuecomment-1225320929.
Before we merge this PR, a committer should be involved to transfer all existing issues to the `apache/pulsar` repo.
cc @Anonymitaet @urfreespace @lhotari @michaeljmarshall @dave2wave

Merge pulsar-site issues to the main repo

---

.asf.yaml

Protect these branches from accidentally removing.

Protect master and deployment branches

---

site2/tools/build-site.sh

`VERSION` in `build-site.sh` was set to `latest` by default, but it should be `next` now.

Fix default VERSION error in build-site.sh

---

site2/tools/build-site.sh

This PR moves `release-json-gen.sh` upward so that it can actually take effect.

Fix release json gen script does not work

---

site2/tools/build-site.sh

Since we now move the reference directory to `static/reference`, we need to move reference doc gen scripts forward (before `split-version-build.sh`) as well because they are now part of the main website.

Fix reference doc gen scripts does not work

---

site2/tools/apidoc/python/README.md
site2/tools/apidoc/python/pdoc-generator-helper.sh
site2/tools/apidoc/python/pdoc-generator.sh
site2/tools/apidoc/python/pydoctor-generator-helper.sh
site2/tools/apidoc/python/pydoctor-generator.sh

This closes https://github.com/apache/pulsar/issues/18347.
cc @michaeljmarshall please take a look.

Document how to generate apidoc python

---

site2/website-next/docs/client-libraries.md
site2/website-next/scripts/replace.js

Workaround Docusaurus links issue
Reported at https://github.com/facebook/docusaurus/issues/8344.
See also https://docusaurus.io/docs/static-assets#in-markdown. `require` causes:
```
Module not found: Error: Can't resolve './../static/api/cpp/3.0.0' in '/pulsar/site2/website-next/docs'
```

Workaround Docusaurus links issue 

---

site2/website-next/static/reference/next/config/README.md

Fixes https://github.com/apache/pulsar/issues/18490
1. Add back the configuration override information introduced in https://github.com/apache/pulsar/pull/15818 but missed on the new [Pulsar config](https://pulsar.apache.org/reference/#/next/config/) site.
2. Add an introductory paragraph in the parent config topic.
The preview looks good:

Add client config override

---

site2/website-next/contribute/validate-release-candidate.md

Since the metadata store has changed from Zk to RocksDB in branch-2.11 or later,  we don't need to validate this step anymore

Update validate release candidate doc

---

site2/website-next/static/examples/openssl.cnf

Copied from https://github.com/apache/pulsar/issues/18656:
There are many url like `wget https://raw.githubusercontent.com/apache/pulsar-site/main/site2/website/static/examples/openssl.cnf` link to the openssl.cnf in the pulsar doc. But this file was deleted at https://github.com/apache/pulsar-site/pull/215.
* Restore the openssl.cnf

Restore openssl.cnf

---

site2/website-next/contribute/validate-release-candidate.md

The gpg command example in `validate-release-candidate` is wrong. This PR fixes it.

Fix gpg command in validate-release-candidate.md

---

site2/website-next/scripts/replace.js

This closes https://github.com/apache/pulsar/issues/18695.

Replace API docs links to major release: BUILD_ALL_VERSION=1

---

site2/website-next/docusaurus.config.js

This closes https://github.com/apache/pulsar/issues/17899.
Reference: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap
cc @urfreespace I don't know whether this change causes unintentional breaking changes, please review.

Add trailingslash for SiteMap URLs

---

site2/website-next/contribute/develop-labels.md

`[CI Testing in Fork](testing-and-ci/personal-ci.md)` is 404. 
This PR corrects it to `[CI Testing in Fork](personal-ci.md)`.
Preview looks good:

[fix][doc] fix 404 URL

---

site2/website-next/src/pages/community.js
site2/website-next/src/pages/contact.js
site2/website-next/src/pages/contributing.md

The Heroku app that was being used to automate the Slack invite of new users has stopped working since Heroku has terminated the free tier.
I've added a new Slack app that does the email invite.

Change link to Slack workspace auto-invite

---

contribute/release-process.md

As https://github.com/apache/pulsar/pull/19101 has modified the shell suffix from `shell` to `bin`, we also need to update here.

Fix shell suffix

---

contribute/release-process.md

[The release process document says JDK 11 is required](https://pulsar.apache.org/contribute/release-process/#preparation), but 17 is supposed to be required for recent releases actually.

[fix][doc] Fix JDK version for release process

---

docs/develop-plugin.md
versioned_docs/version-2.10.x/develop-plugin.md
versioned_docs/version-2.11.x/develop-plugin.md

There is currently no description of adding custom servlets using Pulsar's plugin architecture

[improve][develop-plugin] Add section for AdditionalServlet plugins

---

docs/io-hdfs2-sink.md
docs/io-hdfs3-sink.md

[The HDFS2 sink documentation refers to the `filenamePrefix` configuration as "(Required) true, if compression is set to None"](https://pulsar.apache.org/docs/next/io-hdfs2-sink/#property), but [it's always required actually. Instead, either `fileExtension` or `compression` should be set at least](https://github.com/apache/pulsar/blob/master/pulsar-io/hdfs2/src/main/java/org/apache/pulsar/io/hdfs2/sink/HdfsSinkConfig.java#L96-L99).
[This behaviour is the same for HDFS3](https://github.com/apache/pulsar/blob/master/pulsar-io/hdfs3/src/main/java/org/apache/pulsar/io/hdfs3/sink/HdfsSinkConfig.java#L86-L89
), so its documentation also should be fixed.

[fix][doc] Correct configuration requirements for the HDFS sinks

---

blog/2022-07-12-Apache-Pulsar-2-10-1.md
blog/2022-07-27-Apache-Pulsar-2-9-3.md
blog/2022-09-09-Apache-Pulsar-2-7-5.md
blog/2023-01-09-Apache-Pulsar-2-10-3.md
data/release-pulsar.js

Add the release blog for Pulsar version 2.10.3.

[blog] Add 2.10.3 release blog

---

src/components/downloads.tsx
src/pages/download.mdx

Pulsar 2.11.0 contains Pulsar shell new artifacts and we need make the download links available.
* Added after Pulsar distribution
* One row for unix (.tar.gz) and one for Windows (.zip)
Preview:

Add Pulsar shell to the download page

---

blog/2023-01-20-Apache-Pulsar-2-11-0.md
data/release-pulsar.js

Add the release blog for Pulsar version 2.11.0.

[Blog] Add 2.11 release blog

---

data/users.js

Some logos are not visible on the page. Their URLs are wrong.
I fixed the StreamNative logo URL.
I tried to fix the others, but I'm not 100% sure I would take the right URLs, so I did not fix the other logos in this PR.
Here is the preview:

[fix][doc] fix StreamNative logo URL on /powered-by page

---

docs/admin-api-schemas.md
versioned_docs/version-2.11.x/admin-api-schemas.md

The field name of toggling the schema validation enforced is `isSchemaValidationEnforced`. See [broker.conf](https://github.com/apache/pulsar/blob/8eb7ee1e9e96d4686e452320cdaba92d5eca7b4f/conf/broker.conf#L1502-L1504) and [the code](https://github.com/apache/pulsar/blob/8eb7ee1e9e96d4686e452320cdaba92d5eca7b4f/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java#L2633)
This PR fixes the incorrect name.

[fix][schema] Fix incorrect field name of `isSchemaValidationEnforced`

---

docs/admin-api-namespaces.md
docs/reference-pulsar-admin.md

This supersedes https://github.com/apache/pulsar/pull/19001.

Fix set-persistent admin doc

---

docs/developing-binary-protocol.md
docs/security-authorization.md

Adding docs for https://github.com/apache/pulsar/pull/19455

Document connecting through a proxy

---

docs/getting-started-docker.md
versioned_docs/version-2.11.x/getting-started-docker.md

I know its something small but it really should be able for windows people to simply copy and paste this shell command without needing to do any extra effort like removing the backslashes and making it one line because powershell doesn't support this. If you disagree feel free to decline this.

Easier to copy&paste command for Windows

---

docs/tiered-storage-aliyun.md
docs/tiered-storage-aws.md
docs/tiered-storage-azure.md
docs/tiered-storage-filesystem.md
docs/tiered-storage-gcs.md
docs/tiered-storage-s3.md
versioned_docs/version-2.10.x/tiered-storage-aliyun.md
versioned_docs/version-2.10.x/tiered-storage-aws.md
versioned_docs/version-2.10.x/tiered-storage-azure.md
versioned_docs/version-2.10.x/tiered-storage-filesystem.md
versioned_docs/version-2.10.x/tiered-storage-gcs.md
versioned_docs/version-2.11.x/tiered-storage-aliyun.md
versioned_docs/version-2.11.x/tiered-storage-aws.md
versioned_docs/version-2.11.x/tiered-storage-azure.md
versioned_docs/version-2.11.x/tiered-storage-filesystem.md
versioned_docs/version-2.11.x/tiered-storage-gcs.md
versioned_docs/version-2.11.x/tiered-storage-s3.md
versioned_docs/version-2.8.x/tiered-storage-aliyun.md
versioned_docs/version-2.8.x/tiered-storage-aws.md
versioned_docs/version-2.8.x/tiered-storage-azure.md
versioned_docs/version-2.8.x/tiered-storage-filesystem.md
versioned_docs/version-2.8.x/tiered-storage-gcs.md
versioned_docs/version-2.9.x/tiered-storage-aliyun.md
versioned_docs/version-2.9.x/tiered-storage-aws.md
versioned_docs/version-2.9.x/tiered-storage-azure.md
versioned_docs/version-2.9.x/tiered-storage-filesystem.md
versioned_docs/version-2.9.x/tiered-storage-gcs.md

Correct the default values of the following two parameters for all types of offloaders:
* `managedLedgerMinLedgerRolloverTimeMinutes`
* `managedLedgerMaxEntriesPerLedger`

[fix][doc] correct default values of tiered storage offloaders

---

data/release-cpp.js
src/components/downloads.tsx

The current C++ client download page is wrong, see:
It's because the table uses the `vtag` field to generate the **Release** and **Link** columns. 
https://github.com/apache/pulsar-site/blob/679b203bf481c552dde9d7dd4a932e7309e81d52/src/components/downloads.tsx#L177-L181
However, #419 set them as `3.1.x`. This PR uses the sub string of the `tagName` field instead of the `vtag` field, after the change the download page looks like:

Fix wrong C++ client download page

---

static/reference/next/config/README.md

Related PR: https://github.com/apache/pulsar/pull/18385

[improve][doc] Add doc for `pulsar.enableUring` property

---

static/reference/next/cli.md
static/reference/next/config/README.md
static/reference/next/pulsar-admin/README.md
static/reference/next/pulsar-client/README.md
static/reference/next/pulsar-perf/README.md

This PR:
- Fixes https://github.com/apache/pulsar/issues/19492
- Adds explanations to the homepages of several CLI tools
All previews look good:
cc @momo-jun @DaveDuggins @D-2-Ed

[improve][doc] add instructions of env variables to CLI docs

---

contribute/release-process.md
contribute/validate-release-candidate.md
sidebarsDevelopment.js

Move "Creating GPG key" and "Release note guide" as subpages of "Release process".
Thanks for @Anonymitaet and @momo-jun's suggestion.

[improve][doc] Restructure releases docs

---

docs/client-libraries-clients.md
docs/client-libraries-consumers.md
docs/client-libraries-producers.md

* Add missing example codes for the java client
* Remove `Configure messages` section in the producer doc because it's already covered in `Send mesasges`
I think we also could delete [Send messages with customized metadata section](https://pulsar.apache.org/docs/next/client-libraries-producers/#send-messages-with-customized-metadata) because it's already covered in `Send mesasges`

[Improve][doc] Add missing examples for java client

---

versioned_docs/version-2.11.x/concepts-messaging.md

fix Non-persistent messaging cookbook url 404 error

---

versioned_docs/version-2.10.x/administration-isolation.md
versioned_docs/version-2.10.x/reference-rest-api-overview.md
versioned_docs/version-2.11.x/reference-rest-api-overview.md
versioned_docs/version-2.2.0/reference-rest-api-overview.md
versioned_docs/version-2.2.1/reference-rest-api-overview.md
versioned_docs/version-2.3.0/reference-rest-api-overview.md
versioned_docs/version-2.3.1/reference-rest-api-overview.md
versioned_docs/version-2.3.2/reference-rest-api-overview.md
versioned_docs/version-2.4.0/reference-rest-api-overview.md
versioned_docs/version-2.4.1/reference-rest-api-overview.md
versioned_docs/version-2.4.2/reference-rest-api-overview.md
versioned_docs/version-2.5.0/reference-rest-api-overview.md
versioned_docs/version-2.5.1/reference-rest-api-overview.md
versioned_docs/version-2.5.2/reference-rest-api-overview.md
versioned_docs/version-2.6.0/reference-rest-api-overview.md
versioned_docs/version-2.6.1/reference-rest-api-overview.md
versioned_docs/version-2.6.2/reference-rest-api-overview.md
versioned_docs/version-2.6.3/reference-rest-api-overview.md
versioned_docs/version-2.6.4/reference-rest-api-overview.md
versioned_docs/version-2.7.0/reference-rest-api-overview.md
versioned_docs/version-2.7.1/reference-rest-api-overview.md
versioned_docs/version-2.7.2/reference-rest-api-overview.md
versioned_docs/version-2.7.3/reference-rest-api-overview.md
versioned_docs/version-2.7.4/reference-rest-api-overview.md
versioned_docs/version-2.7.5/reference-rest-api-overview.md
versioned_docs/version-2.8.x/administration-isolation.md
versioned_docs/version-2.8.x/reference-rest-api-overview.md
versioned_docs/version-2.9.x/administration-isolation.md
versioned_docs/version-2.9.x/reference-rest-api-overview.md

Replace the master version (`version=master`) with a variable for specific versions (`version=@pulsar:version_number@`) of REST API docs.

[fix][doc] Replace master version with a variable for specific versions in REST API links

---

docs/admin-api-schemas.md
docs/client-libraries-cpp.md
static/reference/next/pulsar-daemon/pulsar-daemon.md
versioned_docs/version-2.10.x/schema-manage.md
versioned_docs/version-2.11.x/admin-api-schemas.md
versioned_docs/version-2.2.0/schema-manage.md
versioned_docs/version-2.2.1/schema-manage.md
versioned_docs/version-2.3.0/schema-manage.md
versioned_docs/version-2.3.1/schema-manage.md
versioned_docs/version-2.3.2/schema-manage.md
versioned_docs/version-2.4.0/schema-manage.md
versioned_docs/version-2.4.1/schema-manage.md
versioned_docs/version-2.4.2/schema-manage.md
versioned_docs/version-2.5.0/schema-manage.md
versioned_docs/version-2.5.1/schema-manage.md
versioned_docs/version-2.5.2/schema-manage.md
versioned_docs/version-2.6.0/schema-manage.md
versioned_docs/version-2.6.1/schema-manage.md
versioned_docs/version-2.6.2/schema-manage.md
versioned_docs/version-2.6.3/schema-manage.md
versioned_docs/version-2.6.4/schema-manage.md
versioned_docs/version-2.7.0/schema-manage.md
versioned_docs/version-2.7.1/schema-manage.md
versioned_docs/version-2.7.2/schema-manage.md
versioned_docs/version-2.7.3/schema-manage.md
versioned_docs/version-2.7.4/schema-manage.md
versioned_docs/version-2.7.5/schema-manage.md
versioned_docs/version-2.8.x/schema-manage.md
versioned_docs/version-2.9.x/schema-manage.md

Fix https://github.com/apache/pulsar/issues/19697 and https://github.com/apache/pulsar/issues/19675
Preview looks good:
Previews of other versioned docs are not attached. They will be in the correct formats since those contents are written in the same way (markdown).

[fix][doc] resolve doc issues in schema, client, and reference

---

docs/reference-cli-tools.md
scripts/replace.js

issue: https://github.com/apache/pulsar/issues/19676

feat: reference page jump with version

---

versioned_docs/version-2.11.x/administration-pulsar-shell.md
versioned_docs/version-2.11.x/reference-cli-tools.md
versioned_docs/version-2.11.x/security-tls-authentication.md
versioned_docs/version-2.11.x/security-tls-transport.md

update reference link for 2.11.x

---

docs/admin-api-schemas.md

The docs explain that the schema format must be a JSON string of the Avro schema definition. However, it is explained only on the Admin CLI tab but not the REST & Java Client tab. 
This pull request fixes that.
However, this PR contains duplicated text. Is there a way to remove this duplication?

explain the schema format for REST API & Java Admin API

---

docs/reference-terminology.md

[fix][doc] Markdown link in reference-terminology.md

---

docs/security-athenz.md

This is a continuation of https://github.com/apache/pulsar-site/pull/410. I've also added some parameters to the Athenz authentication provider for Golang to support Copper Argos (cf. https://github.com/apache/pulsar-client-go/pull/960), so I'll add sample code for Golang. Also, the existing sample code was wrong, so I fixed it.

[improve][doc] Add sample code to use Copper Argos in Golang

---

docs/client-libraries-cpp-configs.md
docs/client-libraries-node-setup.md
versioned_docs/version-2.11.x/client-libraries-node.md

Fixes https://github.com/apache/pulsar-client-node/issues/306.
The dependency on the CPP library has been removed for the latest Node.js client library.
The purpose of this fix is to:
1. set up simple and correct expectations for users and eliminate noise.
2. make sure the nitty gritty details are single-sourced in the README of the Node.js client lib.
1. remove the out-of-date tips for requiring the CPP client lib.
2. paraphrase the backlink to the README of the Node.js client lib.

[fix][doc] Remove CPP client lib requirements from Node.js client docs

---

docs/client-libraries-python-configs.md

Here are specific links for these configuration doc:
* Client: https://pulsar.apache.org/api/python/3.1.x/pulsar.Client.html#__init__
* Producer: https://pulsar.apache.org/api/python/3.1.x/pulsar.Client.html#create_producer
* Consumer: https://pulsar.apache.org/api/python/3.1.x/pulsar.Client.html#subscribe
* Reader: https://pulsar.apache.org/api/python/3.1.x/pulsar.Client.html#create_reader

[improve][doc] Add configurations doc for the python client

---

contribute/about.md

Added short description of what is a PIP and liked to the page detailing it and its process

[fix][doc] Add link to PIP to Contribute page

---

src/theme/DocPage/index.js
src/theme/DocPage/index.tsx

This closes https://github.com/apache/pulsar/issues/18190.
Here are some screenshots for the result:
The "canonical" link are the only element in head metadata, no duplicate or confusion.

[feat] Add canonical link for SEO

---

docs/functions-cli.md

1. Add a new config `skipToLatest` to function docs, following https://github.com/apache/pulsar/pull/17214/.
2. Add a new config `compressionType` to function docs, following https://github.com/apache/pulsar/pull/19470.
Local preview:

[feat][doc] Add new configs `skipToLatest` and `compressionType`

---

docs/concepts-messaging.md
versioned_docs/version-2.10.x/concepts-messaging.md
versioned_docs/version-2.11.x/concepts-messaging.md
versioned_docs/version-2.8.x/concepts-messaging.md
versioned_docs/version-2.9.x/concepts-messaging.md

1. Highlight and clarify the scope of delayed msg delivery.
2. Minor fixes and style alignment.

[improve][doc] Clarify the scope of delayed msg delivery

---

docs/admin-api-clusters.md
docs/deploy-bare-metal.md
docs/reference-terminology.md

Many thanks to @hangc0276 for providing technical support! 
There are some issues in the current [Admin API > Features > Clusters](https://pulsar.apache.org/docs/next/admin-api-clusters/) doc. I’ve summarized them with the corresponding solutions below.
Issues | Solutions
-- | --
Some docs are inaccurate and make users confused | Correct the description
Some "Concept"-type docs are shown in Sub-features, while they should be located elsewhere in Pulsar docs. | Move and consolidate them to the correct place. For example, move "Concept"-type docs to [Reference > Terminology](https://pulsar.apache.org/docs/next/reference-terminology/).
Some operations are in chaotic order. | Categorize operations logically to match users' learning pace. For example, classify operations based on the CRUD …

[improve][doc] Optimize "Admin API > Features > Clusters"

---

src/theme/DocPage/index.tsx

I still searched some ancient versions on Google. Perhaps the canonical link trick doesn't work or it needs more time to propagate. But let's add more meta to help the search engine not index unmaintained pages.
2.9.x (unmaintained):
2.10.x, 2.11.x, and NEXT don't have this meta tag.

[feat] noIndex unmaintained pages for SEO

---

docs/concepts-messaging.md
versioned_docs/version-2.11.x/concepts-messaging.md

Originally the statement may means shared subscriptions include key-shared subscriptions, but shared and key-shared are totally different subscription types.

revise ambiguous statements

---

tools/pytools/README.md
tools/pytools/bin/js-apidoc-generator.py
tools/pytools/lib/execute/typedoc_generator.py

cc @shibd 
This refers to https://github.com/apache/pulsar/issues/19876.
You can test with:
```shell
cd tools/pytools
poetry run bin/js-apidoc-generator.py 1.8.2-rc.1
```
Then, preview on http://localhost:3000/api/js/1.8.x/.
The release process can be updated later.

feat: js doc generator

---

docs/admin-api-clusters.md
docs/admin-api-functions.md
docs/admin-api-schemas.md
docs/admin-get-started.md
docs/how-to-landing.md
sidebars.json

This PR fixes https://github.com/apache/pulsar/issues/20024
I’ve summarized all issues with the corresponding solutions below. 
Issues | Solutions
-- | --
[Get Started of pulsar-admin ](https://pulsar.apache.org/docs/next/get-started-pulsar-admin/)is shown in [Tutorials](https://pulsar.apache.org/docs/next/how-to-landing/). | Relocate it to [Admin API - Get Started](https://pulsar.apache.org/docs/next/admin-api-get-started/) to improve the ease of use.
The wordings "Java admin API" in [Admin API > Features > Functions](https://pulsar.apache.org/docs/next/admin-api-functions/) and [Admin API > Features > Schemas](https://pulsar.apache.org/docs/next/admin-api-schemas/) are inaccurate. | Correct it to "Java".
@labuladong @asafm @jak78 thanks for your technical guidance!
Ping @D-2-Ed to …

[improve][doc] relocate "Get Started" (pulsar-admin) to admin API and correct inaccurate descriptions

---

contribute/create-gpg-keys.md

See the discussion here https://lists.apache.org/thread/f9w430oqpm0g72b1htwbtc8y3mfqf8r6
In addition, download the `KEY` file before appending a KEY because `svn up` might not download the file.

Update the process to upload the GPG key

---

docs/developing-binary-protocol.md

This documentation covers an addition to the Pulsar Protocol. It was added by PIP-250 https://github.com/apache/pulsar/issues/19623 with its implementation here https://github.com/apache/pulsar/pull/19618.

PIP-250: Document proxy_version protocol update

---

docs/client-libraries-clients.md

Fix wrong examples of CPP advertised listeners.

---

docs/client-libraries-producers.md

- https://github.com/apache/pulsar/wiki/PIP-68%3A-Exclusive-Producer
- https://github.com/apache/pulsar-client-cpp/issues/95

Add producer access mode examples for Java and C++ client.

---

release-notes/versioned/pulsar-3.0.0.md

The PR https://github.com/apache/pulsar/pull/19432 wasn't marked with the 3.0.0 milestone. So the 3.0.0 release note didn't include it.
This PR adds it to the 3.0.0 release note.

Add `multi-arch docker images support` to 3.0.0 release note

---

docs/client-libraries-producers.md
versioned_docs/version-3.0.x/client-libraries-producers.md

The current notes look like:
That is because they have an extra space `::: note`. By removing the space, the note will render correctly. Here is my preview:

Fix note annotation to correct rendering

---

docs/security-openid-connect.md
versioned_docs/version-3.0.x/security-openid-connect.md

The OpenID Connect docs need some additional clarifications.

Minor improvements to OIDC docs

---

docs/security-openid-connect.md
versioned_docs/version-3.0.x/security-openid-connect.md

I received some feedback that the client doc section would be better if it pointed to the correct section in the OAuth2 docs. This PR updates the link and also clarifies why the OAuth2 client plugin is recommended.

Improve OIDC client authentication docs

---

docs/client-libraries-clients.md
versioned_docs/version-3.0.x/client-libraries-clients.md

This PR adds doc for https://github.com/apache/pulsar-client-go/pull/991#issuecomment-1512391159

Add client memory limits docs.

---

static/reference/index.html

Found when answering https://github.com/apache/pulsar/issues/20324.

[fix][doc] Add 3.0.x reference docs in sidebar

---

.dockerignore
Dockerfile
docker-compose.yaml
package.json

This PR fixes https://github.com/apache/pulsar/issues/20272
cc @visortelle @asafm welcome to test in your env:
```
docker-compose up
```
... should simply work and you can browse at http://localhost:3000/

build: add containerized building 

---

docs/client-libraries-tableviews.md

Add CPP client table view doc.

---

docs/functions-deploy-cluster-builtin.md
versioned_docs/version-3.0.x/functions-deploy-cluster-builtin.md

Those commands are available starting Pulsar 3.0

Add doc for available-functions and functions reload

---

docusaurus.config.js

After https://github.com/apache/pulsar-site/commit/b30efcce68ceeda50f960cec2a22fe0f1194d233, the Concepts, and Quickstart menu items are both highlighted at the same time.
Looks not good. 🙂
This PR fixes it.
Also, this PR fixes the reason behind https://github.com/apache/pulsar-site/commit/b30efcce68ceeda50f960cec2a22fe0f1194d233.
The Concepts and Quickstart menu items refer to the latest version now instead of `next`.

Fix highlight Quickstart and Concepts menu items at the same time

---

data/books.tsx

This PR fixes a few typos in the Pulsar in Action book description.
I checked the other descriptions but I didn't find issues.

[fix] typos in books.tsx

---

docs/develop-plugin.md
docs/functions-package-java.md
docs/io-develop.md
versioned_docs/version-2.10.x/develop-plugin.md
versioned_docs/version-2.10.x/io-develop.md
versioned_docs/version-2.11.x/develop-plugin.md
versioned_docs/version-2.11.x/functions-package-java.md
versioned_docs/version-2.11.x/io-develop.md
versioned_docs/version-2.8.x/io-develop.md
versioned_docs/version-2.9.x/io-develop.md
versioned_docs/version-3.0.x/develop-plugin.md
versioned_docs/version-3.0.x/functions-package-java.md
versioned_docs/version-3.0.x/io-develop.md

Update nar maven plugin to 1.5.0
Contains fixes such as
https://issues.apache.org/jira/browse/NIFI-10599
https://issues.apache.org/jira/browse/NIFI-11217
With older nifi-nar-maven-plugin versions, the nar file generation "downloads the internet" and is extremely slow together with other updated maven plugins.

[improve][docs] Upgrade nifi-nar-maven-plugin version shown in docs

---

contribute/about.md

Part of PIP-265: https://github.com/apache/pulsar/issues/20207
The new PIP process is now located in `pip/README.md` in Pulsar repo.

Linked to new location of PIP process

---

docs/deploy-monitoring.md
docs/reference-metrics.md
versioned_docs/version-2.10.x/deploy-monitoring.md
versioned_docs/version-2.10.x/reference-metrics.md
versioned_docs/version-2.11.x/deploy-monitoring.md
versioned_docs/version-2.11.x/reference-metrics.md
versioned_docs/version-2.8.x/deploy-monitoring.md
versioned_docs/version-2.8.x/reference-metrics.md
versioned_docs/version-2.9.x/deploy-monitoring.md
versioned_docs/version-2.9.x/reference-metrics.md
versioned_docs/version-3.0.x/deploy-monitoring.md
versioned_docs/version-3.0.x/reference-metrics.md

We will convert the metric prefix `brk_` to `pulsar_` when generating the metrics.
So we don't have `brk_` related metrics.
As most of the users are using Pulsar-2.8 at least, so I just modify the error metrics from 2.8~now

Fix error metric prefix

---

docs/client-libraries.md

Adds a note to the client overview page that mentions the client/broker compatibility.
@michaeljmarshall @lhotari @david-streamlio can you take a peek?

[improve][doc] Add note on client/broker compatibility

---

docs/client-libraries-producers.md

* Restructure the content of the producer doc to make it more reasonable
* Make the content more consistent for all clients
* Fix some minor syntax errors
I have only completed the Java part of the modification. There is some additional work for other clients.
Much of the content has been simplified, but this PR does not(and should not) remove essential feature content.
Here is the temporary preview link: http://review-pulsar-site.zikeyang.com:3000/docs/next/client-libraries-producers/

Restructure the producer doc

---

docs/security-athenz.md

This PR adds doc for https://github.com/apache/pulsar-client-cpp/pull/274
I've added C++ sample code since https://github.com/apache/pulsar-client-cpp/pull/274 will support Copper Argos in the C++ client. This is a similar change to https://github.com/apache/pulsar-site/pull/457.

[improve][doc] Add sample code to use Copper Argos in C++

---

src/components/pages/HomePage/HomePage.tsx
src/components/pages/HomePage/ShortInfo/Parallax/Parallax.tsx
src/components/pages/HomePage/ShortInfo/ShortInfo.module.css
src/components/pages/HomePage/ShortInfo/ShortInfo.tsx
src/components/pages/HomePage/useScrollPosition.tsx

Live demo: https://pulsar-site-pip-249-git-blur-transition-teal-tools.vercel.app/
Feature request: https://apache-pulsar.slack.com/archives/C04UXRZSMHV/p1686493144908659
https://github.com/apache/pulsar-site/assets/9302460/40c8d02b-5809-4e16-bcf2-f375c74f4a10
My only concern for such animations is performance on some devices, especially on mobile.
Please thumb up 👍 if it performs smoothly on your device.
Thumb down 👎 if not.

HomePage - Make the blurry part not be cut, but slowly become blurry as user scrolls to make it a smooth transition.

---

docs/functions-develop-security.md
versioned_docs/version-2.11.x/functions-develop-security.md
versioned_docs/version-3.0.x/functions-develop-security.md

A typo is found at the "Get the secret" section in Enable security on Functions doc: https://pulsar.apache.org/docs/next/functions-develop-security/#get-the-secret.
- [ x ] `doc` 
Before update, it looks like:
After update, the preview looks good：

[doc][improve]--fix typos in get the secret section

---

docs/security-jwt.md
versioned_docs/version-2.10.x/security-jwt.md
versioned_docs/version-2.11.x/security-jwt.md
versioned_docs/version-2.2.1/security-token-client.md
versioned_docs/version-2.3.0/security-token-client.md
versioned_docs/version-2.3.1/security-token-client.md
versioned_docs/version-2.3.2/security-token-client.md
versioned_docs/version-2.4.0/security-jwt.md
versioned_docs/version-2.4.0/security-token-client.md
versioned_docs/version-2.4.1/security-jwt.md
versioned_docs/version-2.4.1/security-token-client.md
versioned_docs/version-2.4.2/security-jwt.md
versioned_docs/version-2.4.2/security-token-client.md
versioned_docs/version-2.5.0/security-jwt.md
versioned_docs/version-2.5.1/security-jwt.md
versioned_docs/version-2.5.2/security-jwt.md
versioned_docs/version-2.6.0/security-jwt.md
versioned_docs/version-2.6.1/security-jwt.md
versioned_docs/version-2.6.2/security-jwt.md
versioned_docs/version-2.6.3/security-jwt.md
versioned_docs/version-2.6.4/security-jwt.md
versioned_docs/version-2.7.0/security-jwt.md
versioned_docs/version-2.7.1/security-jwt.md
versioned_docs/version-2.7.2/security-jwt.md
versioned_docs/version-2.7.3/security-jwt.md
versioned_docs/version-2.7.4/security-jwt.md
versioned_docs/version-2.7.5/security-jwt.md
versioned_docs/version-2.8.x/security-jwt.md
versioned_docs/version-2.9.x/security-jwt.md
versioned_docs/version-3.0.x/security-jwt.md

Fix the python client JWT auth example problem which is missing the commas.

[fix][doc] Pulsar client JWT auth example missing commas

---

docs/developers-landing.md

This PR adds popular topics to the dev landing page to give quick guidance for devs to get familiar with Pulsar.
The popular topics (pages) are based on the data collected from [GA](https://docs.google.com/document/d/1H-wEEfut18M18dle6a4-2EWCnLOqyJ81RVYxkPkTXhk/edit#bookmark=id.8p4o4lxknpyy) and [Matomo](https://matomo.privacy.apache.org/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=32#?idSite=32&period=range&date=2022-11-07,2023-06-13&category=General_Actions&subcategory=General_Pages), which covers from concepts, tasks, and references.

[doc][improve] add popular topics to dev landing page

---

docs/concepts-broker-load-balancing-concepts.md
docs/concepts-broker-load-balancing-overview.md
sidebars.json

1. This PR adds **Overview** for https://github.com/apache/pulsar/issues/20570
Feel free to check related resources:
- [Doc IA | Broker load balancing](https://xmind.works/share/pntJsr7n)
- [Doc Outline | Broker load balancing](https://docs.google.com/document/d/1zshyn93XJp8Y-uvYLTnFCrcUWaHxeiTjPqdaUrR6zf0/edit#heading=h.8e831emctxc8)
2. The next phase is to add **Concepts** for https://github.com/apache/pulsar/issues/20570
---
@heesung-sn @Demogorgon314 thanks for your detailed technical guidance!
@D-2-Ed thanks for your thorough editor review!

[feat][doc] add overview for broker load balancing

---

versioned_docs/version-3.0.x/concepts-messaging.md

Added information about topic retention policies on the tip. 
It forgets to mention that there are actions that can be performed at `topic` level for retention and mislead that it can only be done at namespace level

[fix][doc] Misleading tip about retention, not mentioned topics policies.

---

versioned_docs/version-3.0.x/administration-geo.md

There can be a corner case where 2 consumer subscribe with different type of subscription on each cluster.
The only thing replicated is information about the subscription. Not the type.

[improve][doc] Subscription replication doesn't replicate the type

---

versioned_docs/version-3.0.x/functions-runtime-kubernetes.md

(detailed history: https://github.com/apache/pulsar/discussions/20708)
this PR address these two issues
1. according to the source code, the document uses a deprecated config key.
2. the key is not working on apache pulsar 3.0.0 (while the updated key works)
https://github.com/apache/pulsar/blob/17ea4b8f968d8862cb2c781eaeefc83ff4b25686/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java#L884-L887

[fix][doc] k8s function runtime uses deprecated config key

---

docs/security-openid-connect.md
versioned_docs/version-3.0.x/security-openid-connect.md

This PR fixes the issues raised in https://stackoverflow.com/questions/76633061/apache-pulsar-fails-to-enable-openid-authentication-in-function-worker-when-conf and https://stackoverflow.com/questions/76631732/apache-pulsar-unable-to-validate-issuer-certificate-when-attempting-to-load-open
Fixes:
* The Function worker's `authenticationProviders` takes a list, not a string
* The `openIDTokenIssuerTrustCertsFilePath` config should not be the empty string. This is fixed by https://github.com/apache/pulsar/pull/20745.

OIDC docs fixes

---

docs/reference-metrics.md

This PR adds metrics for the extensible load balancer (topics in the red box below)
This document presents a high-level architecture overview, including how we address content gaps and reconcile existing …

[feat][doc] add metrics for extensible load balancer

---

docs/client-libraries-cluster-level-failover.md
versioned_docs/version-2.10.x/client-libraries-java.md
versioned_docs/version-2.11.x/client-libraries-java.md
versioned_docs/version-3.0.x/client-libraries-cluster-level-failover.md

It's quite weird that on the https://pulsar.apache.org/docs/3.0.x/client-libraries-cluster-level-failover/#automatic-failover code example only includes the secondary cluster auth config without the primary cluster auth. 
And as my check on test code https://github.com/apache/pulsar/blob/2b01f83ea4f3ab7b22f4ea2b0290cc183e79bbb8/pulsar-client/src/test/java/org/apache/pulsar/client/impl/AutoClusterFailoverTest.java#L73 it has the `primaryAuthentication` config creation. 

[fix][doc]: add the primary auth config on cluster failover example 

---

docs/concepts-broker-load-balancing-concepts.md
docs/reference-metrics.md

This PR fixes https://github.com/apache/pulsar/issues/20881
@Demogorgon314 thanks for your technical guidance!

[improve][doc] add explanations of how to expose bundle metrics

---

docs/administration-pulsar-shell.md

This PR fixes the Pulsar Shell directory name in the example.
Copy-pasting the example into a bash shell and running it didn't work because of the invalid directory name in the last line. This PR fixes this problem.

[fix] [doc] Fix the Pulsar Shell directory name in the example

---

docs/concepts-messaging.md
versioned_docs/version-2.10.x/concepts-messaging.md
versioned_docs/version-2.11.x/concepts-messaging.md
versioned_docs/version-2.8.x/concepts-messaging.md
versioned_docs/version-2.9.x/concepts-messaging.md
versioned_docs/version-3.0.x/concepts-messaging.md

This PR fixes https://github.com/apache/pulsar/issues/20612
The default naming rule of Retry topic is `{tenant}/{namespaces}/{topic}-{sub}-RETRY`, see: https://pulsar.apache.org/docs/3.0.x/concepts-messaging/#retry-letter-topic
The rule before version `2.8` was `{tenant}/{namespaces}/{sub}-RETRY`, and if there is a ZK node `/admin/partitioned-topics/{namespace}-RETRY`, Pulsar will still use the rule `{tenant}/{namespaces}/{sub}-RETRY` even if the version of Pulsar is larger than `2.8`.  This part of the explanation is not reflected in the documentation.
**Related PR**
- [#6449 Support Consumers Set Custom Retry Delay](https://github.com/apache/pulsar/pull/6449)
- [#10129 fix the default retry letter and dead letter topic name](https://github.com/apache/pulsar/pull/10129)

[improve] [doc] Add compatibility reminders for retry queues

---

docs/concepts-broker-load-balancing-benefits.md
docs/concepts-broker-load-balancing-concepts.md
docs/concepts-broker-load-balancing-features.md
docs/concepts-broker-load-balancing-migration.md
docs/concepts-broker-load-balancing-overview.md
docs/concepts-broker-load-balancing-types.md
docs/concepts-broker-load-balancing-use-case.md
sidebars.json

This PR adds migration tutorials for broker load balancing (topics in the red box below)
This document presents a high-level architecture overview, including how we address content gaps and reconcile existing …

[feat][doc] add migration tutorials for broker load balancing

---

static/reference/next/config/README.md

This PR adds configurations for broker load balancing (topics in the red box below)
This document presents a high-level architecture overview, including how we address content gaps and reconcile existing …

[feat][doc] add configurations for broker load balancing

---

docs/concepts-broker-load-balancing-benefits.md
docs/concepts-broker-load-balancing-concepts.md
docs/concepts-broker-load-balancing-features.md
docs/concepts-broker-load-balancing-overview.md
docs/concepts-broker-load-balancing-quick-start.md
docs/concepts-broker-load-balancing-types.md
docs/concepts-broker-load-balancing-use-case.md
docs/reference-metrics.md
sidebars.json

This PR adds a quick start for broker load balancing (topics in the red box below)
This document presents a high-level architecture overview, including how we address content gaps and reconcile existing …

[feat][doc] add Quick Start for broker load balancing

---

docs/develop-load-manager.md

This PR adds and optimizes development docs for broker load balancing (topics in the red box below)
This document presents a high-level architecture overview, including how we address content gaps and reconcile …

[feat][doc] add development docs for broker load balancing

---

docs/administration-anti-affinity-namespaces.md
sidebars.json

This PR introduces the following changes (topics in the red box below)
- Removes old docs for broker load balancing, as we've added the new docs and published them on the Pulsar website (https://pulsar.apache.org/docs/next/concepts-broker-load-balancing-concepts/, https://pulsar.apache.org/docs/next/concepts-broker-load-balancing-types/)
- Brings "Anti-affinity namespaces" out of the broker load balancing docs and sets it as an independent section. This is a quick win as it is a copy from the existing doc https://pulsar.apache.org/docs/next/administration-load-balance/#distribute-anti-affinity-namespaces-across-failure-domains
- Create new documentation to cover all aspects of the feature (especially …

[improve][doc] optimize old docs for broker load balancing

---

contribute/develop-labels.md

Update the Pulsar labels explanation according to the [mailing list discussion](https://lists.apache.org/thread/fz31dn050mqjnwjsmflchr2mdtwkthgm)
And the description of the labels is updated.

[improve][doc] Update the Pulsar labels explanation

---

docs/getting-started-helm.md

I followed the steps of the guide '[Run a standalone Pulsar cluster in Kubernetes](https://pulsar.apache.org/docs/3.1.x/getting-started-helm/)' that uses Helm. Unfortunately, I got stuck at step 4 about pulsar-manager. Indeed, pulsar-manager doesn't work following these steps as they are. I encounter the issues described here: https://github.com/apache/pulsar-manager/issues/505 and here: https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1692714198252109
This pull request proposes document corrections so that pulsar-manager works following the guide's steps.

[fix][doc] fix the Helm Getting Started Guide to make pulsar-manager work

---

contribute/develop-labels.md

[fix][doc] Remove duplicated release label description

---

docs/reference-metrics.md

- Add the documentation for how to enable PerChannel BookKeeper Client metrics
- Add more exposed metrics to the metrics table

[improve] Improve the BookKeeper Client Metrics doc

---

docs/adaptors-kafka.md
docs/adaptors-spark.md
docs/adaptors-storm.md

SEO for Adaptors

---

versioned_docs/version-3.1.x/io-http-sink.md

Fix typo in HTTP sink connector

---

src/theme/DocSidebar/Desktop/styles.module.css
src/theme/DocSidebar/Mobile/styles.module.css

This PR polishes the version switch on desktop.
The previous style reduced the clickable area, making it inconvenient for users to interact. 
And made changes to the pointer style, emphasizing its clickability by using the "pointer" cursor.
Before:
After:

Polish version switch on desktop

---

docs/reference-metrics.md
versioned_docs/version-2.10.x/reference-metrics.md
versioned_docs/version-2.11.x/reference-metrics.md
versioned_docs/version-3.0.x/reference-metrics.md
versioned_docs/version-3.1.x/reference-metrics.md

Fix docs for pulsar_subscription_back_log and pulsar_subscription_unacked_messages

[fix][doc] Fix 2 subscription metric docs

---

docs/admin-api-schemas.md

This PR improves the following page: https://pulsar.apache.org/docs/next/admin-api-schemas/#upload-a-schema
The PR specifies the allowed values for the `type` and `schema` fields of the schema payload used by the upload admin endpoint.

[improve][doc] clarify the usage of the schema admin API

---

data/team.js

Process used to update `data/team.js` file:
1. Logged in to https://whimsy.apache.org/roster/committee/pulsar with browser
2. Appended ".json" to URL so that browser goes to https://whimsy.apache.org/roster/committee/pulsar.json
3. Clicked "Save as..." and stored the JSON as ~/Downloads/pulsar.json
4. Ran this command in a bash shell: `{ echo -n "module.exports = " && cat ~/Downloads/pulsar.json | jq '{"pmc": [.roster| to_entries | sort_by(.key) | .[] | select(.value.role|startswith("PMC")) | {"name":.value.name, "apacheId": .key}], "committers": [.roster| to_entries | sort_by(.key) | .[] | select(.value.role=="Committer") | {"name":.value.name, "apacheId": .key}]}' } | perl -pe 's/$/;\n/ if eof' > data/team.js`

Sync data/team.js with https://whimsy.apache.org/roster/committee/pulsar.json

---

data/release-cpp.js
release-notes/versioned/client-cpp-3.4.1.md

Add the release note for C++ client 3.4.1

---

versioned_docs/version-3.1.x/security-encryption.md

golang client: only RSA keys are supported
func (d *DefaultMessageCrypto) addPublicKeyCipher(keyName string, keyReader KeyReader) error {
d.cipherLock.Lock()
defer d.cipherLock.Unlock()
if keyName == "" || keyReader == nil {
return fmt.Errorf("keyname or keyreader is null")
}
// read the public key and its info using keyReader
keyInfo, err := keyReader.PublicKey(keyName, nil)
if err != nil {
return err
}
parsedKey, err := d.loadPublicKey(keyInfo.Key())
if err != nil {
return err
}
// try to cast to RSA key
rsaPubKey, ok := parsedKey.(*rsa.PublicKey)
if !ok {
return fmt.Errorf("only RSA keys are supported")
}
encryptedDataKey, err := rsa.EncryptOAEP(sha1.New(), rand.Reader, rsaPubKey, d.dataKey, nil)
if err != nil {
return err
}
d.encryptedDataKeyMap.Store(keyName, …

[fix][doc]Update security-encryption.md for key pairs of golang

---

contribute/validate-release-candidate.md

- Stop the Cassandra container after the Cassandra connector test
- Add validation for source tarball
- Add BookKeeper JNI libs check according to the [discussion](https://lists.apache.org/thread/gsbh95b2d9xtcg5fmtxpm9k9q6w68gd2)

Improve the Pulsar release verify doc

---

contribute/validate-release-candidate.md

`org.apache.bookkeeper-circe-checksum-<version>.jar` and `org.apache.bookkeeper-cpu-affinity-<version>.jar` are under the folder `{PULSAR_HOME}/lib`, not `{PULSAR_HOME}`

Fix wrong path define Pulsar release verify doc

---

data/release-pulsar.js

This PR fixes https://github.com/apache/pulsar/issues/21677

Fix the release tables for 3.0.2

---

docs/security-athenz.md

This PR adds doc for https://github.com/apache/pulsar-client-cpp/pull/274
Python client v3.3.0 and next release version of Node.js client support Copper Argos because they use cpp client v3.3.0 or above.
Therefore, I add sample codes for Copper Argos in python/Node.js.
<br>
I previewed my changes locally and they appeared as expected.
**1. description**
**2. python sample code**
**3. Node.js sample code**

[improve][doc]Add athenz copper argos sample code in python/nodejs

---

contribute/create-gpg-keys.md

The GPG instructions are unclear and some instructions (such as MacOS keychain integration) are missing.
This PR improves the instructions.

Improve GPG instructions in the contribution guide

---

contribute/create-gpg-keys.md

A step was missing in adding the committer's GPG key to KEYS file in the contribution guide

Contribution guide: Add step for importing the committer's public GPG key from the key server

---

client-feature-matrix/index.mdx
data/matrix.js
docs/client-libraries.md
src/components/Matrix/util.js

This PR aims to improve the experience for .NET/C# users looking for information on .NET/C# clients. The goal is to help the users choose which client best suits their needs.
Two .NET clients exist: C#/DotPulsar and .NET client. They don't provide the same feature coverage. The PR fixes the client features matrix to display the two clients side by side to highlight this coverage difference.
Additionally, the PR adds a link to the client docs to facilitate the navigation and help the user compare the two clients in details.
Finally, the PR makes the doc use the same names for the clients in both the feature matrix and the client libraries page to improve clarity.
Preview:

[doc][client feature matrix] improve experience for .NET users looking for information on .NET/C# clients

---

docs/about.md
src/components/pages/HomePage/ShortInfo/ShortInfo.tsx
src/pages/download.mdx
versioned_docs/version-2.10.x/about.md
versioned_docs/version-2.11.x/about.md
versioned_docs/version-2.8.x/about.md
versioned_docs/version-2.9.x/about.md
versioned_docs/version-3.0.x/about.md
versioned_docs/version-3.1.x/about.md

cc @markt-asf 
According to your suggestions:
> 1. While "Apache® Pulsar™" is strictly correct, it can also look a
> little awkward / busy so it is OK to use "Apache Pulsar™" if you prefer.
Thank you! Although I don't have a strong feeling, with point 2 below the refer to "Apache® Pulsar™" in homepage is not the first and most prominent usage so I accept your suggestion. Other occurrences of "Apache® Pulsar™" if any doesn't change.
> 2. Pages such as https://pulsar.apache.org/ should use "Apache Pulsar™"
> for the "Apache Pulsar" in blue text since that is both the first and
> most prominent usage.
I can't read "such as" so I handle exactly the homepage. Now the "Apache Pulsar" in blue text is changed to "Apache Pulsar™":
> 3. The documentation pages such as …

[improve][misc] ASF branding

---

data/release-python.js
release-notes/versioned/client-python-3.4.0.md

This PR adds the release note for Python client 3.4.0

Add the release note for Python client 3.4.0

---

docs/concepts-messaging.md
versioned_docs/version-2.10.x/concepts-messaging.md
versioned_docs/version-2.11.x/concepts-messaging.md
versioned_docs/version-3.0.x/concepts-messaging.md
versioned_docs/version-3.1.x/concepts-messaging.md

In Pulsar, the ledger will be deleted automatically after the messages in this ledger have been consumed. Pulsar will delete the front ledgers of a topic but will not delete ledgers from the middle of a topic. It means that if you send a message that is delayed for a long time, the message will not be consumed until it reaches the delay time. This means all the ledgers on this topic could not be deleted until the delayed message is consumed, even if some subsequent ledgers are fully consumed.

[doc] Avoid users send messages with too long delay time

---

docs/concepts-messaging.md
versioned_docs/version-2.10.x/concepts-messaging.md
versioned_docs/version-2.11.x/concepts-messaging.md
versioned_docs/version-3.0.x/concepts-messaging.md
versioned_docs/version-3.1.x/concepts-messaging.md

After using delayed messages, it is advisable to exercise caution when using the Backlog Quota strategy.  This is because delayed messages can result in messages not being consumed for an extended period, triggering the Backlog Quota strategy and causing subsequent message sends to be rejected.

[doc] Add a note: if using Delayed messages, advisable to exercise caution when using the Backlog Quota strategy

---

docs/cookbooks-compaction.md

Explain the retain policy of messages without keys for compaction.

[improve][doc] Explain retain policy of messages without keys for compaction

---

contribute/validate-release-candidate.md
docs/io-quickstart.md
versioned_docs/version-2.10.x/io-quickstart.md
versioned_docs/version-2.11.x/io-quickstart.md
versioned_docs/version-2.2.0/io-quickstart.md
versioned_docs/version-2.2.1/io-quickstart.md
versioned_docs/version-2.3.0/io-quickstart.md
versioned_docs/version-2.3.1/io-quickstart.md
versioned_docs/version-2.3.2/io-quickstart.md
versioned_docs/version-2.4.0/io-quickstart.md
versioned_docs/version-2.4.1/io-quickstart.md
versioned_docs/version-2.4.2/io-quickstart.md
versioned_docs/version-2.5.0/io-quickstart.md
versioned_docs/version-2.5.1/io-quickstart.md
versioned_docs/version-2.5.2/io-quickstart.md
versioned_docs/version-2.6.0/io-quickstart.md
versioned_docs/version-2.6.1/io-quickstart.md
versioned_docs/version-2.6.2/io-quickstart.md
versioned_docs/version-2.6.3/io-quickstart.md
versioned_docs/version-2.6.4/io-quickstart.md
versioned_docs/version-2.7.0/io-quickstart.md
versioned_docs/version-2.7.1/io-quickstart.md
versioned_docs/version-2.7.2/io-quickstart.md
versioned_docs/version-2.7.3/io-quickstart.md
versioned_docs/version-2.7.4/io-quickstart.md
versioned_docs/version-2.7.5/io-quickstart.md
versioned_docs/version-2.8.x/io-quickstart.md
versioned_docs/version-2.9.x/io-quickstart.md
versioned_docs/version-3.0.x/io-quickstart.md
versioned_docs/version-3.1.x/io-quickstart.md

When validating 3.2.0 release, I noticed that the instructions no longer worked for the Cassandra connector steps. The problem was fixed by using `cassandra:3.11` container instead of `cassandra:latest`.
Update examples to use `cassandra:3.11` container.

Fix examples that use cassandra docker container

---

contribute/release-process.md

After https://github.com/apache/pulsar/pull/20981, running `mvn clean install -DskipTests` doesn't produce source tarball. But it would be packaged and staged under the SVN dir following the instructions below.
Update docs to reduce confusion.

[improve][docs] release-process wording

---

docs/deploy-bare-metal.md

Add explanation for using multiple ZooKeeper server in BookKeeper metadataServiceUri setting
Ref: https://github.com/apache/bookkeeper/issues/1756

[improve][doc] Explain how to use mutiple ZooKeeper in BookKeeper metadataServiceUri settings

---

docs/getting-started-docker-compose.md

This PR adds doc for #[getting-started-docker-compose](https://pulsar.apache.org/docs/next/getting-started-docker-compose/)
This PR fixes #[getting-started-docker-compose](https://pulsar.apache.org/docs/next/getting-started-docker-compose/)

 [fix][doc] auth problem in getting-started-docker-compose.md

---

docusaurus.config.js

I think the previous one is not correct.
After:

chore: update footer to fix the ASF's full name

---

contribute/release-process.md

The current release docker images process doesn't work for Pulsar above versions 3.0.0. Pulsar has added arm and amd arch supports for the docker image. If we use the original command to push the image, it will push only one arch.
We recommend use tools like regctl to push images.
For the latest tag of the pulsar image, this PR proposes to use the last feature release version or the patch release of the last feature release as the `latest` tag.

[fix] Update release docker image in release process

---

docs/security-encryption.md
versioned_docs/version-3.0.x/security-encryption.md
versioned_docs/version-3.1.x/security-encryption.md

The command in the document does not work for OpenSSL 1.1 or 3.2.
```bash
$ openssl rsa -in test_rsa_privkey.pem -pubout -outform pkcs8 -out test_rsa_pubkey.pem
rsa: Bad format "pkcs8"
rsa: Invalid format "pkcs8" for option -outform
rsa: Use -help for summary.
$ openssl --version
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)
$ /opt/homebrew/opt/openssl@1.1/bin/openssl rsa -in test_rsa_privkey.pem -pubout -outform pkcs8 -out test_rsa_pubkey2.pem
rsa: Invalid format "pkcs8" for -outform
rsa: Use -help for summary.
$ /opt/homebrew/opt/openssl@1.1/bin/openssl version
OpenSSL 1.1.1w  11 Sep 2023
```

Fix incorrect command to generate public key for end-to-end encryption

---

src/components/pages/CaseStudiesPage/Cards/Cards.tsx

I made this change according to the approved design in Figma that adds external link icons to cards on the Case Studies page: https://pulsar.apache.org/case-studies/

Open Case Studies links in new tab

---

docs/txn-advanced-features.md

This PR adds doc for https://github.com/apache/pulsar/pull/21114

[improve][doc]Add introduction of transaction isolation level in the txn-advanced-features.md

---

src/components/ui/ArticleThumb/ArticleThumb.js
src/components/ui/ArticleThumb/ArticleThumb.module.css
src/css/docs.css

It's rather an idea.
**Goals:**
- Allow users to quickly ask a question in the right place.
- Improve the documentation by encouraging users to report unclear or incomplete parts of the documentation.
Try it live: https://pulsar-site-2024-updates-7uwroc4qs-visortelle.vercel.app/docs/next/concepts-cluster-level-failover/
If there are too many questions, we can change the link to another Google-indexable place like https://github.com/apache/pulsar/discussions/categories/q-a
Alternatively, we could add more links to doc page's bottom section that encourages users to communicate with Pulsar developers and the community:
https://docs.confluent.io/platform/current/clients/index.html

Add the "I don't understand it" link

---

src/components/ui/ArticleThumb/ArticleThumb.js
src/components/ui/ArticleThumb/ArticleThumb.module.css

A variation of this PR: https://github.com/apache/pulsar-site/pull/807
Suggest changes -> new GitHub issue with the "Document" template
Get Support -> new GitHub discussion in Q&A section

Add "Suggest changes" and "Get support" links

---

contribute/site-intro.md
data/powered-by.ts
src/components/pages/CaseStudiesPage/CaseStudiesPage.tsx
src/components/pages/EcosystemPage/EcosystemPage.tsx
src/components/pages/EventsPage/EventsPage.tsx
src/components/pages/HomePage/ShortInfo/ShortInfo.module.css
src/components/pages/HomePage/ShortInfo/ShortInfo.tsx
src/components/pages/PoweredByPage/PoweredByPage.tsx
src/components/pages/ResourcesPage/ResourcesPage.tsx
src/components/ui/ContributeDataDrivenPage/ContributeDataDrivenPage.module.css
src/components/ui/ContributeDataDrivenPage/ContributeDataDrivenPage.tsx
src/pages/team.js
src/utils/index.js

The "Case Studies" section is currently placed at the bottom of the home page.
I think it's good for the project to show that many companies use Pulsar at the very beginning of the page.
This PR adds this block to the first homepage screen.
Live demo: https://pulsar-site-2024-updates-git-case-studies-at-top-visortelle.vercel.app/
I'm not sure if is it allowed to mention specific companies. We can somehow rephrase the text if not.
- Apache Pinot has such a block that mentions LinkedIn on the homepage.
- Apache Kafka has it at the top of its homepage.
cc: @dave2wave @lhotari

Add case studies link at the top of the home page

---

docs/txn-use.md
versioned_docs/version-3.0.x/txn-use.md
versioned_docs/version-3.1.x/txn-use.md
versioned_docs/version-3.2.x/txn-use.md

The main change is:
```diff
-- [Start Pulsar 2.8.0 or later versions](#getting-started-standalone.md)
+- [Start Pulsar 2.8.0 or later versions](getting-started-standalone.md)
```
The rest of the diff removes trailing spaces at the line endings and between paragraphs.

Fix broken link

---

docs/tiered-storage-overview.md
versioned_docs/version-2.11.x/tiered-storage-overview.md
versioned_docs/version-3.0.x/tiered-storage-overview.md
versioned_docs/version-3.1.x/tiered-storage-overview.md
versioned_docs/version-3.2.x/tiered-storage-overview.md

This PR emphasizes that Pulsar clients can still transparently read the data in the offloaded ledgers.
This should remove possible confusion, [as seen here](https://github.com/apache/pulsar/discussions/22113).

[fix][doc] Highlights that Pulsar clients can seamlessly access data in offloaded ledgers.

---

src/components/pages/BooksPage/BooksPage.tsx
src/components/pages/CaseStudiesPage/CaseStudiesPage.tsx
src/components/pages/CommunityPage/CommunityPage.tsx
src/components/pages/EcosystemPage/EcosystemPage.tsx
src/components/pages/EventsPage/EventsPage.tsx
src/components/pages/HomePage/HomePage.tsx
src/components/pages/PoweredByPage/PoweredByPage.tsx
src/components/pages/ResourcesPage/ResourcesPage.tsx
src/css/typography.css

The purpose of this change is to increase the amount of content that fits on the screen.
The lack of horizontal space makes it hard to read table content on documentation pages.
Discussion: https://github.com/apache/pulsar/discussions/22155
Global `LandingPage` CSS class is introduced to keep the `18px` font size on the "promotional" pages according to the original design. Maybe not the fully correct class name, but easy to understand and grep.

Change font-size from 18px to 16px in docs

---

contribute/release-process.md
contribute/setup-building.md
contribute/setup-mergetool.md
sidebarsDevelopment.js

For Apache Pulsar core developers, handling git merge conflict resolution is necessary. 
To efficiently resolve merge conflicts, setting up tools that assist in visualizing these conflicts and resolving them is essential.  
This is a document which hopefully is useful for at least release managers when they have to deal with merge conflicts.
This document is attached in the navigation under "Release process".

Add contributor documentation for setting up git mergetool

---

docs/cookbooks-deduplication.md
versioned_docs/version-2.11.x/cookbooks-deduplication.md
versioned_docs/version-3.0.x/cookbooks-deduplication.md
versioned_docs/version-3.1.x/cookbooks-deduplication.md
versioned_docs/version-3.2.x/cookbooks-deduplication.md

The explanation doesn't remark this is a requirement as mentioned in the design:
https://github.com/apache/pulsar/wiki/PIP-6%3A-Guaranteed-Message-Deduplication#design
This PR fixes [apache/pulsar#22210](https://github.com/apache/pulsar/issues/22210)

[improve][doc] Dedup section needs to remark that producer name is a requirement

---

contribute/release-process.md
static/.htaccess

- Updated the `/docs` redirect from `3.1.x` to `3.2.x`
- Added instructions on how to update redirect to the release process documentation 
- Fixed a few trailing spaces in a markdown doc

Update /docs redirect

---

docs/about.md
versioned_docs/version-3.0.x/about.md
versioned_docs/version-3.2.x/about.md

---
Asked by @jak78 in this comment: <https://github.com/apache/pulsar-site/pull/808#issuecomment-1973270309>

Describe ways to improve the documentation

---

contribute/release-policy.md

- added notice, as per discussion on the mailing list, https://lists.apache.org/thread/y6ct7446d3d91w0ph7pqrk54xy6p1pq6
- moved the supported versions to the beginning of the page

Add notice about supported versions of Pulsar on the release policy page

---

src/components/SupportedVersionsTable.tsx
src/pages/download.mdx

It probably makes sense to place the release schedule and supported versions in a more visible place to regular users.
Now users should perform the following trip to get this info: Download -> Release Notes -> Release Policy
The Release Policy page is on the `/contribute/release-policy/` route, but it's unlikely that most of the users are contributors.
Also, there is no way to figure out which version is LTS from the `/download` page.
- Show supported versions on the `/download` page
---
Show all versions on the `/contribute/release-policy` (no changes here)

Show supported versions on download page

---

data/release-cpp.js
release-notes/versioned/client-cpp-3.5.0.md

Add the release note for C++ client 3.5.0

---

data/team.js
scripts/sync-team-js.sh
src/components/pages/CommunityPage/CommunityPage.tsx

There seems to be a hardcoded ApacheID -> GitHub ID mappings: https://github.com/apache/pulsar-site/blob/d7e1e218f025fa8ad3f3a88c03eb9ec3cafe1a81/src/components/pages/CommunityPage/CommunityPage.tsx#L29-L33
This doesn't make sense since the GitHub usernames are available from ASF.
In ASF, it's possible to have multiple GitHub user ids so that's the reason why it's an array.
- add script for updating information from ASF Whimsy's pulsar.json data file

Add GitHub user ids for committers and PMC members to team.js

---

docs/schema-overview.md
versioned_docs/version-2.11.x/schema-overview.md
versioned_docs/version-3.0.x/schema-overview.md
versioned_docs/version-3.1.x/schema-overview.md
versioned_docs/version-3.2.x/schema-overview.md

According to the [Client Features Matrix](https://pulsar.apache.org/client-feature-matrix/), the Node.Js client supports schemas.

[fix][doc] specifies that the Node client supports schemas

---

src/components/pages/HomePage/Users/Users.tsx

- show a different testimonial each time the page renders

Shuffle testimonials before displaying them

---

docs/concepts-broker-load-balancing-concepts.md

Added a split example

---

docs/client-libraries-cluster-level-failover.md
versioned_docs/version-2.10.x/client-libraries-java.md
versioned_docs/version-2.11.x/client-libraries-java.md
versioned_docs/version-3.0.x/client-libraries-cluster-level-failover.md
versioned_docs/version-3.1.x/client-libraries-cluster-level-failover.md
versioned_docs/version-3.2.x/client-libraries-cluster-level-failover.md

Cluster failover Java client is available for 2.10.0 and later versions.
This PR fixes example code shown in [Automatic-failover](https://pulsar.apache.org/docs/3.2.x/client-libraries-cluster-level-failover/#automatic-failover) and [Controlled-failover](https://pulsar.apache.org/docs/3.2.x/client-libraries-cluster-level-failover/#controlled-failover)
It adds required ServiceUrlProvider while building PulsarClient
`.serviceUrlProvider(failover)`

[fix][doc] Fixes example code in Cluster Failover Java Client

---

data/connectors.js

Fixes https://github.com/apache/pulsar/issues/22229
The artifact pulsar-io-netty-3.2.1.nar appears twice on the download page with different descriptions.

Remove duplicate pulsar-io-netty nar on download page

---

docusaurus.config.js
src/components/pages/CommunityPage/sections/discussions/DiscussionPlatforms.module.css
src/components/ui/renderAnnouncementBar.js
src/css/announcement-bar.css

- Ask for joining the Pulsar community at the announcement bar. The link refers to the [Discussion section at the community page](https://pulsar.apache.org/community/#section-discussions).
- Minor style changes at at the community page according to the Figma design
**Before**
**After**

Remove Pulsar Summit EU 2024 announcement bar

---

docs/deploy-bare-metal.md
versioned_docs/version-3.0.x/deploy-bare-metal.md
versioned_docs/version-3.1.x/deploy-bare-metal.md
versioned_docs/version-3.2.x/deploy-bare-metal.md

Always use the multiple zookeeper server address in the bare deployment documentation. Users might don't know much details about the the differences between single zookeeper server address and multiple zookeeper server address. It will be a risk for user if they applied the single zookeeper server address in production. The configured zookeeper server crash will cause the bookie cluster shutdown due to the zookeeper connection issue.

Always use multiple zookeeper server address in the deployment doc

---

docs/reference-metrics.md
versioned_docs/version-3.2.x/reference-metrics.md

Removed mentions of old metric `pulsar_broker_throttled_connections_global_limit` (removed as part of https://github.com/apache/pulsar/pull/21681).
Removed duplicate mention of Broker connection metrics.

[improve][doc] Cleanup broker connection metrics documentation

---

docs/helm-deploy.md
versioned_docs/version-2.10.x/helm-deploy.md
versioned_docs/version-2.11.x/helm-deploy.md
versioned_docs/version-3.0.x/helm-deploy.md
versioned_docs/version-3.1.x/helm-deploy.md
versioned_docs/version-3.2.x/helm-deploy.md
versioned_docs/version-3.3.x/helm-deploy.md

This fixes pulsar-helm-chart issue [442](https://github.com/apache/pulsar-helm-chart/issues/442). The change to use a dependent Helm chart for Prometheus and Grafana was introduced in Helm version [3.0.0](https://github.com/apache/pulsar-helm-chart/releases/tag/pulsar-3.0.0) which shipped with version 2.10.2 of Pulsar by default. I updated the versioned documentation up to that point.
I also added some documentation improvements from a recent Kubernetes deployment. Since I only improved documentation and didn't fix incorrect documentation, I didn't add these changes into any versioned docs.
Changes to monitoring components in the Helm Deployment documentation
Other updates:
I am assuming the version tag didn't resolve since this is running on the development server

Fix out of date Helm documentation around monitoring component customization

---

docs/deploy-monitoring.md

[feat][doc] PIP-264: Update OpenTelemetry deployment documentation

---

docs/concepts-broker-load-balancing-quick-start.md
versioned_docs/version-3.1.x/concepts-broker-load-balancing-quick-start.md
versioned_docs/version-3.2.x/concepts-broker-load-balancing-quick-start.md
versioned_docs/version-3.3.x/concepts-broker-load-balancing-quick-start.md

1. Add a line separator in Segment **Configure broker load balancer to run automatically - Step 4.2**  
Before change:
```bash
bin/pulsar-admin tenants create my-tenant-1 
bin/pulsar-admin namespaces create my-tenant-1/my-namespace-1 --bundles 1 bin/pulsar-admin topics create-partitioned-topic persistent://my-tenant-1/my-namespace-1/my-topic-1 -p 2000
```
After change:
```bash
bin/pulsar-admin tenants create my-tenant-1
bin/pulsar-admin namespaces create my-tenant-1/my-namespace-1 --bundles 1
bin/pulsar-admin topics create-partitioned-topic persistent://my-tenant-1/my-namespace-1/my-topic-1 -p 2000
```
2. Fix typos in Segment **Configure broker load balancer to run manually - Step 4.2**
- `public/default/0x00000000_0x8000000` -> `public/default/0x00000000_0x08000000`
- `bin/pulsar-admin …

Fix typos in concepts-broker-load-balancing-quick-start.md

---

docs/admin-api-topics.md

add topic naming note

---

docs/reference-metrics-opentelemetry.md

[feat][doc] PIP-264: Add OpenTelemetry messaging rate limit metrics reference

---

docs/cookbooks-retention-expiry.md
versioned_docs/version-2.10.x/cookbooks-retention-expiry.md
versioned_docs/version-2.11.x/cookbooks-retention-expiry.md
versioned_docs/version-3.0.x/cookbooks-retention-expiry.md
versioned_docs/version-3.1.x/cookbooks-retention-expiry.md
versioned_docs/version-3.2.x/cookbooks-retention-expiry.md
versioned_docs/version-3.3.x/cookbooks-retention-expiry.md

The namespace level data retention policy is not clear for topic partitions. Users might think the size of the retention is for the whole partitioned topic, but it actually applied to all the partitions of a partitioned topic. For example, if you set the retention policy to 10GB, that means each partition of a partitioned topic will retain 10GB data.

Clarify the data retention policy for topic and partitions

---

docs/txn-use.md
versioned_docs/version-3.0.x/txn-use.md
versioned_docs/version-3.1.x/txn-use.md
versioned_docs/version-3.2.x/txn-use.md
versioned_docs/version-3.3.x/txn-use.md

[improve][doc] add golang transaction demo in txn-use.md

---

data/release-node.js
release-notes/versioned/pulsar-client-node-1.12.0.md

Add the release note for Nodejs client 1.12.0

---

docs/functions-develop-security.md

This updates the following page https://pulsar.apache.org/docs/next/functions-develop-security/ to document an example for the upcoming changes in this (currently in-review) pulsar PR: https://github.com/apache/pulsar/pull/22768

[feat][doc] Update functions-develop-security to include a Go example

---

README.md
contribute/document-contribution.md
scripts/docs-tool.sh
scripts/supported-versions.js

This PR adds a helper script that wraps `git diff` and `patch` for applying committed docs directory changes to versioned_docs directory. This makes it easier to synchronize documentation changes to the documentation of the supported versions.

Add docs-tool.sh for applying committed docs directory changes to versioned_docs directory

---

docs/administration-pulsar-manager.md
versioned_docs/version-3.0.x/administration-pulsar-manager.md
versioned_docs/version-4.0.x/administration-pulsar-manager.md

fix(docs): correct tar command in Pulsar Manager installation guide

---

docs/administration-pulsar-shell.md
docs/client-libraries-cpp.md
docs/getting-started-standalone.md
docs/io-canal-source.md
docs/io-rabbitmq-source.md
src/components/ConnectorTable.js
src/components/ReleaseTable.js
versioned_docs/version-3.0.x/administration-pulsar-shell.md
versioned_docs/version-3.0.x/client-libraries-cpp.md
versioned_docs/version-3.0.x/getting-started-standalone.md
versioned_docs/version-3.0.x/io-canal-source.md
versioned_docs/version-3.0.x/io-rabbitmq-source.md
versioned_docs/version-4.0.x/administration-pulsar-shell.md
versioned_docs/version-4.0.x/client-libraries-cpp.md
versioned_docs/version-4.0.x/getting-started-standalone.md
versioned_docs/version-4.0.x/io-canal-source.md
versioned_docs/version-4.0.x/io-rabbitmq-source.md

Fixed https://github.com/apache/pulsar/issues/23710, following [the guide][1] use `closer.lua` link in download instructions.
[1]: https://infra.apache.org/release-download-pages.html#links

Avoid link to apache archive server directly

---

data/release-cpp.js
release-notes/versioned/client-cpp-3.7.0.md

It also fixes the wrong 3.6.0 document link:

Add release note for CPP client 3.7.0

---

docs/concepts-messaging.md
versioned_docs/version-3.3.x/concepts-messaging.md
versioned_docs/version-4.0.x/concepts-messaging.md

Issue: https://github.com/apache/pulsar-client-go/issues/1297
Root issue: https://github.com/apache/pulsar/pull/21589
New default dlq producer names are in the form of `opt.Name = fmt.Sprintf("%s-%s-%s-%s-DLQ", r.topicName, r.subscriptionName, r.consumerName, generateRandomName())` in branch `4.0.x` and `3.3.x`(https://github.com/apache/pulsar/pull/23645), so that we need to update related documents as well.
Current
https://pulsar.apache.org/docs/4.0.x/concepts-messaging/#dead-letter-topic
Preview

Update default dlq producer name

---

docs/concepts-messaging.md
versioned_docs/version-3.0.x/concepts-messaging.md
versioned_docs/version-3.3.x/concepts-messaging.md
versioned_docs/version-4.0.x/concepts-messaging.md

Add a 30s ackTimeout when using dlq policy: https://github.com/apache/pulsar/pull/3014
Remove this 30s ackTimeout: https://github.com/apache/pulsar/pull/19486
Relative  https://github.com/apache/pulsar/issues/8484  https://github.com/apache/pulsar/issues/19134 
When we are using a Java sdk from 2.3.x to 2.10.x to create a subscription with dlq policy, the subscription will create a 30s ackTimeout policy automatically. This strategy may lead to consuming duplicate messages especially in some long time cost tasks.
According to the comment https://github.com/apache/pulsar/issues/8484#issuecomment-726057120, I think maybe we can add a hint about this 30s ackTimeout policy in concepts-messaging.md dlq section.
Current
Preview

Add note about Java sdk 2.x dlq has a default 30s ackTimeout policy

---

docs/security-athenz.md
versioned_docs/version-4.0.x/security-athenz.md

The Athenz auth plugin for each client library obtains a token for authentication from ZTS. In Java and Go, it is now possible to specify a proxy URL for accessing ZTS as an option, so I have added a description of this.
- https://github.com/apache/pulsar/pull/23947
- https://github.com/apache/pulsar-client-go/pull/1360

Add description of option to specify Athenz ZTS proxy

---

.github/workflows/ci-precommit.yml
data/release-go.js
release-notes/versioned/pulsar-client-go-0.16.0.md
scripts/release_notes_reorder_script.py

- Add go client release notes for 0.16.0
- Fix license isuse introduced by https://github.com/apache/pulsar-site/commit/76575abadab326e9411900e09591a7865bdd14fa
- Add license check for push event

Add go client release notes for 0.16.0

---

static/.htaccess

GitHub badge images (stars, last commit) are not displaying on the client libraries page (https://pulsar.apache.org/docs/next/client-libraries/) due to Content Security Policy (CSP) restrictions blocking requests to `img.shields.io`.
The Apache httpd server's CSP policy does not include the `https://*.shields.io/` domain in the allowed image sources, causing all image requests from `img.shields.io` to be blocked by browsers.
Add `https://*.shields.io/` to the `CSP_PROJECT_DOMAINS` environment variable in the `static/.htaccess` file:
**Before:**
```apache
SetEnv CSP_PROJECT_DOMAINS "https://*.algolia.net/ https://*.algolianet.com/ https://*.algolia.io/"
```
**After:**
```apache
SetEnv CSP_PROJECT_DOMAINS "https://*.algolia.net/ https://*.algolianet.com/ https://*.algolia.io/ …
```

Fix CSP blocking GitHub badge images on client libraries page
