apache/pulsar-site

site2/website-next/docusaurus.config.js, site2/website-next/scripts/split-version.js, site2/website-next/src/pages/index.js, site2/website-next/src/theme/Root.js
Signed-off-by: LiLi <urfree@apache.org>
=> fix: use waves lib with cdn

site2/website-next/docusaurus.config.js, site2/website-next/src/css/custom.css, site2/website-next/src/pages/index.js, site2/website-next/tailwind.config.js
I left some config updates out of my previous pull request.  I also corrected a few styles that were pointed out to me.  
I added the sineWaves import back to the index.js file because it was failing without it.
=> config and style updates

site2/website-next/scripts/.htaccess
Adjustments to .htaccess.
Also going to move the `.htaccess` file to the top level
=> Adjust .htaccess

site2/website-next/scripts/.htaccess
Flags are described here: https://httpd.apache.org/docs/current/rewrite/flags.html
I'm making a PR to better expose the fix.
=> Fixed Rewrites by adding flags [R=301,DPI,L]

site2/website-next/src/css/custom.css
fix: https://github.com/apache/pulsar-site/issues/13
=> fix: Logo and navigation menu bar overlap

site2/website-next/src/pages/download.js
migrate change from https://github.com/apache/pulsar/pull/14855
=> fix: download links fix

site2/website-next/package.json
=> feat: upgrade docusaurus to 2.0.0-beta.18

site2/website-next/scripts/release-notes-other.js, site2/website-next/scripts/release-notes.js, site2/website-next/scripts/release-notes.sh
=> feat: supported specifying component and version for release notes generating

site2/website-next/release-notes/all.md, site2/website-next/scripts/release-notes.js
=> fix: release notes optimize

site2/website-next/docusaurus.config.js
=> fix: edit url

site2/website-next/docs/about.md
Fixed links in lines 43 and 45. Updated URL in line 43; added brackets to descriptor text in line 45.
=> Fixed broken links

site2/website-next/release-notes/all.md, site2/website-next/release-notes/legacy.md
=> feat: add release notes legacy

site2/website-next/src/css/custom.css
=> fix: some link click fail

site2/website-next/data/ecosystem.js, site2/website-next/docusaurus.config.js, site2/website-next/src/components/EcoCards.js, site2/website-next/src/css/custom.css, site2/website-next/src/pages/community.js, site2/website-next/src/pages/contributing.md, site2/website-next/src/pages/ecosystem.js, site2/website-next/src/utils/index.js
Wrapping classes have been moved to the html element.  The style sheet needed to be updated to reflect that change.  This pull request fixes the various layout issues that appeared recently.
=> Fixing broken styles

site2/website-next/src/css/custom.css, site2/website-next/src/pages/community.js
Refactoring image carousel. Added pagination as requested
=> adding pagination to carousel

site2/website-next/preview.sh
=> feat: local preview script

site2/website-next/docusaurus.config.js
=> fix: migrate algolia to new credencials

site2/website-next/src/pages/ecosystem.js
=> [improve][website] Update Ecosystem Page Intro

site2/tools/docker-build-site.sh
=> feat: update docker build image

site2/website-next/src/css/custom.css
Implemented task 1 in apache/pulsar#15550. Screenshot:
=> Add line number in code blocks

site2/website-next/docusaurus.config.js
Implemented task 3 in apache/pulsar#15550. Screenshot:
Not sure which background color and text color are suitable. Please let me know if these colors need to be changed.
=> Add announcement bar

site2/website-next/src/components/CaseStudyCards.js, site2/website-next/src/css/custom.css, site2/website-next/src/pages/case-studies.js, site2/website-next/src/pages/ecosystem.js
Complete two（Add filters to the [Ecosystem](https://pulsar.apache.org/ecosystem) and the [Case Studies](https://pulsar.apache.org/case-studies) pages） from https://github.com/apache/pulsar/issues/15550
I removed the original filtering method, because it will cause duplication
=> Add filters to the Ecosystem and the Case Studies pages

site2/website-next/src/pages/case-studies.js, site2/website-next/src/pages/ecosystem.js
=> fix filter

site2/website-next/docusaurus.config.js
The key does not match. I'm checking for other issues before I merge this
=> Update Algolia API Key

site2/website-next/src/css/custom.css
=> update style for navbar

site2/website-next/docusaurus.config.js
=> Add link to Apache Privacy Policy

site2/website-next/src/pages/download.js
=> [improve][website] add download links for previous versions

site2/website-next/src/pages/contributing.md
This was originally approved by https://github.com/apache/pulsar/pull/15535.
=> Recommitted the dropped instruction, CI Testing in your Fork

site2/tools/publish-website.sh, site2/website-next/scripts/.gitignore, site2/website-next/scripts/split-version-build.sh
clean all the old random js files because a new all version build done, all the js is regenerated with a random name
=> update build scripts for clean all the old random js files because a new all version build done, all the js is regenerated with a random name

site2/tools/pulsar-admin-md.sh, site2/website-next/brodocs/manifest.json
This should fix apache/pulsar#9717
=> fix: add docs generation for pulsar-admin bookies command

site2/website-next/src/css/custom.css
Close apache/pulsar#16180.
Screenshot:
=> Customize tabs and highlight tab sections

site2/website-next/release-notes/all.md, site2/website-next/release-notes/versioned/client-cpp-2.10.1.md, site2/website-next/release-notes/versioned/client-java-2.10.1.md, site2/website-next/release-notes/versioned/client-python-2.10.1.md, site2/website-next/release-notes/versioned/client-websocket-2.10.1.md, site2/website-next/release-notes/versioned/client-websocket-2.9.2.md, site2/website-next/release-notes/versioned/pulsar-2.10.1.md
=> 2.10.1 Release Note

site2/website-next/README.md
I summarized the README content in https://docs.google.com/document/d/1wszdtMRo6MhKbVaggPK7_bnKaC4TewuT--GWZZxJNGg/edit#bookmark=id.rshrr6sdmd56
=> [feat][workflow] add instructions for previewing website changes

site2/website-next/src/css/custom.css
=> Highlight toc when scrolling

site2/website-next/data/team.js, site2/website-next/src/components/TeamTable.js, site2/website-next/src/css/custom.css, site2/website-next/src/pages/community.js
Fix apache/pulsar#15686.
Sorted based on `apacheId`. 
Reference: 
- https://apache-pulsar.slack.com/archives/C02Q4JLUB38/p1650931270994189
- https://people.apache.org/phonebook.html
=> Fix inaccurate community info

site2/website-next/docusaurus.config.js
=> Fix the doc link mismatch problem.

site2/website-next/brodocs/stylesheet.css
Improve brodocs style to work with apache/pulsar#16853.
=> Improve brodocs style

site2/website-next/data/resources.js
Hi,
I would like to submit a blog to the Pulsar website.
Thanks.
FYI. This is the preview image:
=> [Blog] Add a Pulsar blog

site2/tools/pulsar-config-doc-gen.sh
Fix wrong path in pulsar-config-doc-gen.sh. @urfreespace
=> Fix wrong path in pulsar-config-doc-gen.sh

site2/tools/pulsar-config-doc-gen.sh
Fix non-existing directory in pulsar-config-doc-gen.sh. @urfreespace
=> Fix non-existing directory in pulsar-config-doc-gen.sh

site2/tools/pulsar-config-doc-gen.sh
Remove exec command in pulsar-config-doc-gen.sh so that the docs can be successfully generated. @urfreespace
=> Remove exec command in pulsar-config-doc-gen.sh

site2/website-next/scripts/replace.js, site2/website-next/src/utils/index.js
https://github.com/apache/pulsar/issues/16637
=> fix version replace

site2/tools/build-site.sh, site2/tools/pulsar-admin-doc-gen.sh, site2/tools/pulsar-admin-md.sh, site2/tools/pulsar-client-doc-gen.sh, site2/tools/pulsar-client-md.sh, site2/tools/pulsar-config-doc-gen.sh, site2/tools/pulsar-doc-gen.sh, site2/tools/pulsar-md.sh, site2/tools/pulsar-perf-doc-gen.sh, site2/tools/pulsar-perf-md.sh, site2/website-next/docsify/index.html
=> Move config docs to /reference and improve docs gen scripts

site2/website-next/src/css/custom.css, site2/website-next/static/swagger/restApiVersions.json
https://github.com/apache/pulsar-site/issues/173
=> update css for table bg color

site2/website-next/src/components/CommonTable.js, site2/website-next/src/components/ConnectorTable.js, site2/website-next/src/components/GuideTable.js, site2/website-next/src/components/MailTable.js, site2/website-next/src/components/OldReleaseTable.js, site2/website-next/src/components/ReleaseTable.js, site2/website-next/src/components/VersionsTable.js, site2/website-next/static/swagger/restApiVersions.json
=> fix: update table text color in dark model

.github/workflows/ci-pulsar-website-next-build.yaml, site2/tools/publish-website.sh
This refers to #175 and resolves https://github.com/apache/pulsar-site/pull/179#issuecomment-1228636515.
I don't know whether or not it causes some regressions I'm unaware of. Please help with reviews @urfreespace @michaeljmarshall @dave2wave
=> [build][site] cleanup previous content before copy new ones

site2/tools/pulsar-admin-doc-gen.sh, site2/tools/pulsar-client-doc-gen.sh, site2/tools/pulsar-config-doc-gen.sh, site2/tools/pulsar-doc-gen.sh, site2/tools/pulsar-perf-doc-gen.sh
Fix website build error caused by #184.
The reason is currently under investigation.
=> Fix website build error

.asf.yaml
=> Set notifications and merge buttons

site2/website-next/src/css/custom.css, site2/website-next/src/theme/DocVersionBanner/index.js
https://github.com/apache/pulsar/issues/17501
=> Version banner in docs pages

site2/tools/pulsar-config-doc-gen.sh
=> Fix typo in pulsar-config-doc-gen script

content/.htaccess
This closes https://github.com/apache/pulsar/issues/17791
cc @lhotari @dave2wave @michaeljmarshall @lhotari
=> Redirect develop-binary-protocol to developing-binary-protocol

content/charts/index.yaml
This closes https://github.com/apache/pulsar/issues/17799.
=> Add back charts/index.yaml

site2/tools/publish-website.sh
This content is manually checked in.
=> Do not remove charts on full build

site2/website-next/docusaurus.config.js
cc @urfreespace @michaeljmarshall @momo-jun @Anonymitaet @merlimat
=> change the 'Docs' button in navbar dest to latest stable version

site2/website-next/scripts/sync-docs.sh
This refers to https://github.com/apache/pulsar/issues/17817.
=> Stop sync blogs as the truth is now on pulsar-site

site2/website-next/src/pages/events.js
Update the featured event for Pulsar Summit Asia 2022.
=> Update Pulsar featured event for Pulsar Summit Asia 2022

site2/website-next/docsify/2.10.0/pulsar-admin/_sidebar.md, site2/website-next/docsify/2.10.0/pulsar-client/_sidebar.md, site2/website-next/docsify/2.10.0/pulsar-perf/_sidebar.md, site2/website-next/docsify/2.10.0/pulsar/_sidebar.md, site2/website-next/docsify/2.6.0/pulsar-admin/_sidebar.md, site2/website-next/docsify/2.6.0/pulsar-client/_sidebar.md, site2/website-next/docsify/2.6.0/pulsar-perf/_sidebar.md, site2/website-next/docsify/2.6.0/pulsar/_sidebar.md, site2/website-next/docsify/2.7.0/pulsar-admin/_sidebar.md, site2/website-next/docsify/2.7.0/pulsar-client/_sidebar.md, site2/website-next/docsify/2.7.0/pulsar-perf/_sidebar.md, site2/website-next/docsify/2.7.0/pulsar/_sidebar.md, site2/website-next/docsify/2.8.0/pulsar-admin/_sidebar.md, site2/website-next/docsify/2.8.0/pulsar-client/_sidebar.md, site2/website-next/docsify/2.8.0/pulsar-perf/_sidebar.md, site2/website-next/docsify/2.8.0/pulsar/_sidebar.md, site2/website-next/docsify/2.9.0/pulsar-admin/_sidebar.md, site2/website-next/docsify/2.9.0/pulsar-client/_sidebar.md, site2/website-next/docsify/2.9.0/pulsar-perf/_sidebar.md, site2/website-next/docsify/2.9.0/pulsar/_sidebar.md, site2/website-next/docsify/_sidebar.md, site2/website-next/docsify/index.html, site2/website-next/docsify/latest/pulsar-admin/_sidebar.md, site2/website-next/docsify/latest/pulsar-client/_sidebar.md, site2/website-next/docsify/latest/pulsar-perf/_sidebar.md, site2/website-next/docsify/latest/pulsar/_sidebar.md
@Anonymitaet This PR improves TOC style and also use normal fonts for CLI tools like `pulsar-admin` instead of monospaced fonts.
=> Improve TOC style

site2/tools/release-json-gen.sh, site2/website-next/data/release-cpp.js, site2/website-next/data/release-cs.js, site2/website-next/data/release-java.js, site2/website-next/data/release-pulsar.js, site2/website-next/data/release-python.js, site2/website-next/data/release-ws.js, site2/website-next/release-notes/all.md, site2/website-next/src/components/ClientReleaseTable.js, site2/website-next/src/components/PulsarReleaseTable.js
@urfreespace @Anonymitaet PTAL.
=> Fix release table versioning and style issues

site2/website-next/src/theme/DocVersionBanner/index.js
@tisonkun @Anonymitaet @SignorMercurio PTAL, thanks
=> hide top banner on non-docs page

.github/workflows/ci-pulsar-website-next-build.yaml, site2/tools/publish-website.sh
This refers to https://github.com/apache/pulsar/issues/17974.
cc @urfreespace 
Also, please help check if `site2/website-next/scripts/write-redirect.js` still valid or we can simplify the logic.
=> trim more i18n content

site2/website-next/docusaurus.config.js
blog sources have been changed.
cc @Anonymitaet @urfreespace
=> fix blog edit url

site2/tools/release-json-gen.sh, site2/website-next/release-notes/versioned/client-websocket-2.6.0.md
Add missing docs for Websocket Client 2.6.0.
@Anonymitaet PTAL.
=> Add client-websocket-2.6.0.md

site2/website-next/docs/about.md, site2/website-next/docusaurus.config.js, site2/website-next/src/components/BlockLink.js, site2/website-next/src/components/HomepageFeatures.js, site2/website-next/src/components/PillButton.js, site2/website-next/src/components/PromoCallout.js, site2/website-next/src/components/SubHeroBlock.js, site2/website-next/src/pages/index.js
=> correct homepage link and remove dangling bottom block

site2/tools/build-site.sh, site2/tools/publish-website.sh
fixed build error, detail https://github.com/apache/pulsar-site/actions/runs/3317429325/jobs/5480293467
=> fix build error caused by cp swagger dir

.github/workflows/ci-pulsar-website-next-build.yaml, site2/tools/build-site.sh, site2/tools/docker-build-site.sh, site2/tools/publish-website.sh
Verifying on the fork...
See also https://github.com/apache/pulsar-site/pull/264#issuecomment-1289916571
=> fix build process to release content in a correct layout

site2/website-next/docusaurus.config.js, site2/website-next/src/pages/events.js
Add the registration link for Pulsar Summit Asia 2022.
Preview:
=> Update banner event for Pulsar Summit Asia 2022

site2/website-next/docusaurus.config.js, site2/website-next/matomoClientModule.js, site2/website-next/static/js/matomo-agent.js
This closes https://github.com/apache/pulsar/issues/15664.
Later, we should observe data reported to https://matomo.privacy.apache.org/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=32.
cc @urfreespace @dave2wave @Anonymitaet
=> Add Matomo agent

site2/website-next/docusaurus.config.js
Revert https://github.com/apache/pulsar-site/pull/277
=> Revert this dark light switch mode 

site2/website-next/package.json
=> Upgrade Docusaurus to 2.2.0 for all the goods

site2/website-next/docs/cookbooks-encryption.md, site2/website-next/docs/schema-manage.md, site2/website-next/docs/standalone.md, site2/website-next/package.json, site2/website-next/src/libs/useLocationParentPath.js, site2/website-next/versioned_docs/version-2.10.x/standalone.md
This patch is based on #280 (There is no logical dependency, but my local env :)).
This closes https://github.com/apache/pulsar/issues/18410.
=> fix redirections with/without trailing slash

site2/website-next/docusaurus.config.js, site2/website-next/package.json, site2/website-next/src/libs/useLocationParentPath.js, site2/website-next/src/libs/useLocationParentPath.ts, site2/website-next/tsconfig.json
I believe introducing TypeScript support can help us develop the website.
cc @urfreespace 
Verify locally with `./preview.sh 2.10.x` and `yarn build` with `yarn serve`.
=> Add TypeScript support 

site2/website-next/data/release-cpp.js, site2/website-next/release-notes/versioned/client-cpp-3.0.0.md
=> Add release notes for C++ client 3.0.0

site2/website-next/docusaurus.config.js
=> Fix broken links

site2/website-next/contribute/release-process.md
Since 2.11.0 there are two new artifacts for Pulsar shell
=> Include Pulsar shell in the release process

site2/website-next/static/reference/next/pulsar-shell/pulsar-shell.md
Doc related to: https://github.com/apache/pulsar/pull/18608
=> Add doc for Pulsar shell clone

site2/website-next/static/.htaccess
This closes https://github.com/apache/pulsar/issues/18725.
=> server-side redirections for missing pages

site2/website-next/docs/reference-cli-tools.md, site2/website-next/scripts/httpd.conf, site2/website-next/static/.htaccess
=> Setup server-side redirects for missing pages

site2/website-next/contribute/document-preview.md
=> [improve][doc] add workflow for previewing content

site2/website-next/contribute/release-process.md, tools/pytools/README.md, tools/pytools/bin/rest-apidoc-generator.py, tools/pytools/lib/execute/swagger_generator.py
=> Accept version parameter when generating swagger files

site2/website-next/data/release-cpp.js, site2/website-next/release-notes/versioned/client-cpp-3.1.0.md
=> Add the release note for C++ client 3.1.0

site2/website-next/blog/2022-12-01-pulsar-summit-asia-2022-recap.md, site2/website-next/data/team.js
https://home.apache.org/phonebook.html?uid=cbornet
=> Add missing cbornet to committers

site2/website-next/contribute/release-process.md, tools/pytools/bin/reference-doc-generator.py
This closes https://github.com/apache/pulsar/issues/18696.
=> Update release process for references/API docs generation 

site2/website-next/docusaurus.config.js, site2/website-next/src/pages/events.js
Update the top banner and events page
Preview:
=> Update the top banner and events page

site2/website-next/data/release-python.js, site2/website-next/release-notes/versioned/client-python-3.0.0.md
=> Add the release note for Python client 3.0.0

site2/website-next/contribute/release-process.md
Fix broken URL and add the Maven version
=> Fix broken url

.github/actions/sync-content/action.yml, tools/pytools/README.md, tools/pytools/bin/site-updater.py, tools/pytools/poetry.lock, tools/pytools/pyproject.toml
=> downgrade python version requirement to 3.8 for pytools

docs/admin-api-namespaces.md
This is for https://github.com/apache/pulsar/pull/18663.
cc @vineeth1995
=> [improve][admin] unloadNamespaceBundle now accepts destinationBroker param

data/release-node.js, release-notes/versioned/pulsar-client-node-1.8.0.md
=> Add the release note for Nodejs client 1.8.0

docs/client-libraries-java.md
PR [#18375](https://github.com/apache/pulsar/pull/18375) added non-persistent topic support for table view.
=> [improve] Add note for using non-persistent topic in TableView

.github/actions/check-license-header/action.yml, .github/workflows/ci-dummy-sync.yml, .github/workflows/ci-precommit.yml, tools/ci/licenserc.toml, tools/pytools/lib/execute/__init__.py
This refers to https://github.com/apache/pulsar/issues/19064.
=> ci: run sync-without-push separately 

.github/workflows/ci-build-site.yml, .github/workflows/ci-precommit.yml, tools/pytools/bin/site-publisher.py, tools/pytools/bin/site-updater.py, tools/pytools/lib/execute/site_builder.py, tools/pytools/lib/execute/site_uploader.py
* This closes https://github.com/apache/pulsar/issues/19186.
* This closes https://github.com/apache/pulsar/issues/19185.
There are still some issues with catching changed files, but it's inherited from the original script. Maybe revisit later. (And we can always build all)
=> [build][pytools] Build site and precommit

tools/pytools/lib/execute/javadoc_generator.py
=> Add 2.11.0 to javadoc generator black list

data/team.js
Process used to update `data/team.js` file:
1. Logged in to https://whimsy.apache.org/roster/committee/pulsar with browser
2. Appended ".json" to URL so that browser goes to https://whimsy.apache.org/roster/committee/pulsar.json
3. Clicked "Save as..." and stored the JSON as ~/Downloads/pulsar.json
4. Ran this command in a bash shell:
```bash
{ echo -n "module.exports = " && cat ~/Downloads/pulsar.json | jq '{"pmc": [.roster| to_entries | sort_by(.key) | .[] | select(.value.role|startswith("PMC")) | {"name":.value.name, "apacheId": .key}], "committers": [.roster| to_entries | sort_by(.key) | .[] | select(.value.role=="Committer") | {"name":.value.name, "apacheId": .key}]}' } | perl -pe 's/$/;\n/ if eof' > data/team.js
```
=> Update Pulsar PMC members and committers

versioned_docs/version-2.11.x/getting-started-docker.md
changed to 2.11.0 from 2.10.0 in the example
example won't work with 2.10.0, but works with 2.11.0
=> version mismatch

docs/client-libraries-python.md
Add doc for https://github.com/apache/pulsar/pull/17128
=> [Python] Add doc for python chunking feature

docs/client-libraries-java.md, versioned_docs/version-2.10.x/client-libraries-java.md, versioned_docs/version-2.11.x/client-libraries-java.md
Fixes: https://github.com/apache/pulsar/issues/19073
=> [fix][doc] update cluster failover code snippet

.github/workflows/ci-documentbot
This closes https://github.com/apache/pulsar/issues/19103.
=> ci: Add Documentation Bot

blog/2023-02-02-pulsar-virtual-summit-europe-2023-cfp.md
Submitted a blog about Pulsar Summit Europe CFP.
Previews:
=> [BLOG] Add the Pulsar Summit Europe CFP blog

docs/reference-pulsar-admin.md
The document update of https://github.com/apache/pulsar/pull/19300
Please review this pr only if https://github.com/apache/pulsar/pull/19300 has been merged.
=> [improve][doc] improve `pulsar-admin namespaces set-backlog-quota`

data/team.js
Process used to update `data/team.js` file:
1. Logged in to https://whimsy.apache.org/roster/committee/pulsar with browser
2. Appended ".json" to URL so that browser goes to https://whimsy.apache.org/roster/committee/pulsar.json
3. Clicked "Save as..." and stored the JSON as ~/Downloads/pulsar.json
4. Ran this command in a bash shell: 
```bash
{ echo -n "module.exports = " && cat ~/Downloads/pulsar.json | jq '{"pmc": [.roster| to_entries | sort_by(.key) | .[] | select(.value.role|startswith("PMC")) | {"name":.value.name, "apacheId": .key}], "committers": [.roster| to_entries | sort_by(.key) | .[] | select(.value.role=="Committer") | {"name":.value.name, "apacheId": .key}]}' } | perl -pe 's/$/;\n/ if eof' > data/team.js
```
=> Sync data/team.js with https://whimsy.apache.org/roster/committee/pulsar.json

data/connectors.js
=> [fix] Add HTTP sink in connector table

src/components/CommunityPage/sections/discussions/DiscussionPlatforms.tsx
=> 🐞 Fix mail list subscribe/unsubscribe links

docs/reference-metrics.md, static/reference/next/pulsar-daemon/pulsar-daemon.md, versioned_docs/version-2.10.x/reference-metrics.md, versioned_docs/version-2.11.x/reference-metrics.md, versioned_docs/version-2.4.0/reference-metrics.md, versioned_docs/version-2.4.1/reference-metrics.md, versioned_docs/version-2.4.2/reference-metrics.md, versioned_docs/version-2.5.0/reference-metrics.md, versioned_docs/version-2.5.1/reference-metrics.md, versioned_docs/version-2.5.2/reference-metrics.md, versioned_docs/version-2.6.0/reference-metrics.md, versioned_docs/version-2.6.1/reference-metrics.md, versioned_docs/version-2.6.2/reference-metrics.md, versioned_docs/version-2.6.3/reference-metrics.md, versioned_docs/version-2.6.4/reference-metrics.md, versioned_docs/version-2.7.0/reference-metrics.md, versioned_docs/version-2.7.1/reference-metrics.md, versioned_docs/version-2.7.2/reference-metrics.md, versioned_docs/version-2.7.3/reference-metrics.md, versioned_docs/version-2.7.4/reference-metrics.md, versioned_docs/version-2.7.5/reference-metrics.md, versioned_docs/version-2.8.x/reference-metrics.md, versioned_docs/version-2.9.x/reference-metrics.md
This PR:
- Fixes https://github.com/apache/pulsar/issues/19512 (thanks @horizonzy for providing technical inputs!)
- Adds missing `/` to broker metrics doc (thanks @hangc0276 for raising this up!)
cc @momo-jun @DaveDuggins @D-2-Ed
=> [improve][doc] add flag instructions to pulsar-daemon

docs/concepts-messaging.md, versioned_docs/version-2.11.x/concepts-messaging.md
Fixes: https://github.com/apache/pulsar/issues/19567
https://github.com/apache/pulsar/pull/16202 supports chunking in shared subscription, so remove the this line in documents after 2.11 version:
```
Chunking is only available for the exclusive and failover subscription types
```
=> [fix][doc] Shared subscription support chunking

docs/concepts-messaging.md
The URL was not working so updated it
=> Updated the Hashing Scheme url

data/team.js
* Update `data/team.js` by following steps
1. stored https://whimsy.apache.org/roster/committee/pulsar.json to `~/Downloads`
2. ran this command to convert pulsar.json to team.js:
```sh
{ echo -n "module.exports = " && cat ~/Downloads/pulsar.json | jq '{"pmc": [.roster| to_entries | sort_by(.key) | .[] | select(.value.role|startswith("PMC")) | {"name":.value.name, "apacheId": .key}], "committers": [.roster| to_entries | sort_by(.key) | .[] | select(.value.role=="Committer") | {"name":.value.name, "apacheId": .key}]}' } | perl -pe 's/$/;\n/ if eof' > team.js
```
=> [doc] Update committers in data/team.js

docs/schema-get-started.md
Current page:
PR preview page:
=> [fix][doc]: fix golang schema sample format

src/components/RestApi.js, src/utils/index.js
close: https://github.com/apache/pulsar/issues/19644
=> fix rest api page crash

src/utils/index.js
https://github.com/apache/pulsar-site/pull/439#discussion_r1119752768
=> fix: optimize version regex

src/utils/index.js
This fixes https://github.com/apache/pulsar/issues/19681.
This follows up https://github.com/apache/pulsar-site/pull/439. See  https://github.com/apache/pulsar-site/pull/439#discussion_r1122562371.
Verified locally.
=> fix: handle version=master case

docs/cookbooks-retention-expiry.md, versioned_docs/version-2.10.x/cookbooks-retention-expiry.md, versioned_docs/version-2.11.x/cookbooks-retention-expiry.md, versioned_docs/version-2.2.0/cookbooks-retention-expiry.md, versioned_docs/version-2.2.1/cookbooks-retention-expiry.md, versioned_docs/version-2.3.0/cookbooks-retention-expiry.md, versioned_docs/version-2.3.1/cookbooks-retention-expiry.md, versioned_docs/version-2.3.2/cookbooks-retention-expiry.md, versioned_docs/version-2.4.0/cookbooks-retention-expiry.md, versioned_docs/version-2.4.1/cookbooks-retention-expiry.md, versioned_docs/version-2.4.2/cookbooks-retention-expiry.md, versioned_docs/version-2.5.0/cookbooks-retention-expiry.md, versioned_docs/version-2.5.1/cookbooks-retention-expiry.md, versioned_docs/version-2.5.2/cookbooks-retention-expiry.md, versioned_docs/version-2.6.0/cookbooks-retention-expiry.md, versioned_docs/version-2.6.1/cookbooks-retention-expiry.md, versioned_docs/version-2.6.2/cookbooks-retention-expiry.md, versioned_docs/version-2.6.3/cookbooks-retention-expiry.md, versioned_docs/version-2.6.4/cookbooks-retention-expiry.md, versioned_docs/version-2.7.0/cookbooks-retention-expiry.md, versioned_docs/version-2.7.1/cookbooks-retention-expiry.md, versioned_docs/version-2.7.2/cookbooks-retention-expiry.md, versioned_docs/version-2.7.3/cookbooks-retention-expiry.md, versioned_docs/version-2.7.4/cookbooks-retention-expiry.md, versioned_docs/version-2.7.5/cookbooks-retention-expiry.md, versioned_docs/version-2.8.x/cookbooks-retention-expiry.md, versioned_docs/version-2.9.x/cookbooks-retention-expiry.md
Fixes https://github.com/apache/pulsar/issues/19685
=> [improve][doc] Add limitTime example for java admin backlog quota setting

blog/2023-01-20-Apache-Pulsar-2-11-0.md, release-notes/versioned/pulsar-2.11.0.md
This can easily surprise users and we've received several reports.
=> [improve][doc] Highlight JDK17 requirement for 2.11

docs/client-libraries-cpp-initialize.md, docs/client-libraries-python-initialize.md
Add initialization doc for CPP and Python client.
=> [improve][doc] Add initialization doc for CPP and Python client

docs/security-athenz.md, versioned_docs/version-2.11.x/security-athenz.md
In https://github.com/apache/pulsar/pull/19445, I added some new parameters to the authentication plugin for Athenz, so I added a description about them.
=> [improve][doc] Add description for using Copper Argos

docs/functions-package-java.md, versioned_docs/version-2.11.x/functions-package-java.md
This fixes https://github.com/apache/pulsar/issues/19680.
=> [fix][doc] Version requriements for functions java pom.xml

contribute/validate-release-candidate.md
=> [improve][doc] Make the release verification process clearer

data/release-node.js, release-notes/versioned/pulsar-client-node-1.8.1.md
=> Add the release note for Nodejs client 1.8.1

docs/client-libraries-cpp-configs.md
=> [improve][doc] Add configurations doc for the cpp client

versioned_docs/version-2.11.x/about.md
Fix https://github.com/apache/pulsar/issues/19809
cc @momo-jun @DaveDuggins
=> [fix][doc] fix dev landing page link error

data/release-python.js, release-notes/versioned/client-python-3.1.0.md
=> Add the release note for Python client 3.1.0

docs/get-started-pulsar-admin.md, docs/how-to-landing.md, sidebars.json
Fix https://github.com/apache/pulsar-site/pull/462#issuecomment-1471059775
Previews look good:
=> [improve][doc] tweak structure for admin API and CLI

contribute/release-process.md
This closes https://github.com/apache/pulsar/issues/19701.
=> [improve][doc] Verify release candidates in release process

static/robots.txt
This closes https://github.com/apache/pulsar/issues/19107.
=> [improve] Add robots.txt file

docs/client-libraries-go-configs.md
=> [improve][doc] Add go client configs

docs/reference-metrics.md
Add doc for PIP https://github.com/apache/pulsar/pull/19047
=> [improve][doc] Add broker level metrics statistics and expose to prometheus

docs/deploy-bare-metal.md, versioned_docs/version-2.10.x/deploy-bare-metal.md, versioned_docs/version-2.11.x/deploy-bare-metal.md
Fix https://github.com/apache/pulsar/issues/19920
cc @D-2-Ed @niharrathod
=> [improve][doc] clarify usage for metadataStoreUrl

content/robots.txt
NOTE THAT this is for the staged site, not the main website.
=> Block crawler from indexing the staged site

versioned_docs/version-2.11.x/administration-pulsar-manager.md
Amended archive extract command. `-z` removed because it's not gzipped.
=> Update extract pulsar-manager.tar archive command

package.json
This closes https://github.com/apache/pulsar/issues/10801.
=> chore(deps): Upgrade highlight-js to 11.7.0

versioned_docs/version-2.11.x/deploy-bare-metal.md
=> Revise a error statement

docs/admin-api-clusters.md, docs/admin-api-functions.md
There are some issues in the current [Admin API > Features > Functions](https://pulsar.apache.org/docs/next/admin-api-functions/) doc. I’ve summarized them with the corresponding solutions below.
Issues | Solutions
-- | --
Some operations are in chaotic order. | Categorize operations logically to match users' learning pace. <br><br>For example, classify operations based on the CRUD sequence.
Some docs are redundant and scattered. | Consolidate and optimize the explanations.
Some docs are wrongly placed. <br><br>For example, "Concept"-type docs are shown in Sub-features, while they should be located elsewhere in Pulsar docs. | Move and consolidate them to the correct place. 
- 🍊Old structure
- 🍊New structure
🙌Final version
❌Deprecated version
This PR is a part of the "improving the DX and …
=> [improve][doc] Optimize Admin API > Features > Functions

docs/security-jwt.md
=> fix: update jwt examples

docs/txn-advanced-features.md, docs/txn-how.md, docs/txn-monitor.md, docs/txn-use.md, docs/txn-what.md, sidebars.json
Currently, there are some issues in the [Pulsar transactions doc](https://pulsar.apache.org/docs/next/txn-use/) (as stated in https://github.com/apache/pulsar/issues/19996). 
I’ve summarized all issues with the corresponding solutions below. 
Issues | Solutions
-- | --
Get started: doc structure is not clear. | Optimize the doc structure by setting appropriate headings.
Get started: docs are not "MVP" for a quick start. | Move some docs to the newly added topic ("advanced features") to keep learners focused on the minimal info to run it up.
Get started: some examples are incorrect. | Remove old examples and add new steps and examples.
Whole txn doc: sidebar labels are too long. | Streamline them to highlight points and save space.
🍊Old structure VS. 🍊New structure …
=> [feat][doc] Add Get Started for TXN

docs/concepts-messaging.md, versioned_docs/version-2.11.x/concepts-messaging.md
=> [fix] typo omissions concepts-messaging.md

docs/administration-geo.md, docs/client-libraries-cluster-level-failover.md, versioned_docs/version-2.10.x/administration-geo.md, versioned_docs/version-2.10.x/client-libraries-java.md, versioned_docs/version-2.11.x/administration-geo.md, versioned_docs/version-2.11.x/client-libraries-java.md
Fix https://github.com/apache/pulsar/issues/20051
@hangc0276 thanks for your technical explanations!
Ping @D-2-Ed for review, thanks!
=> [improve][doc] Add instructions for enabling replicated subscription

docs/io-rabbitmq-sink.md, docs/io-rabbitmq-source.md, versioned_docs/version-2.10.x/io-rabbitmq-sink.md, versioned_docs/version-2.10.x/io-rabbitmq-source.md, versioned_docs/version-2.11.x/io-rabbitmq-sink.md, versioned_docs/version-2.11.x/io-rabbitmq-source.md
This fixes https://github.com/apache/pulsar/issues/17133.
=> [fix][doc] RabbitMQ source and sink

docs/client-libraries-clients.md, docs/client-libraries-producers.md
=> [Doc] Add C++ doc for client and producer

release-notes/versioned/pulsar-2.10.4.md
=> Fix the release note

package.json, yarn.lock
=> build(deps): Remove redundant dependency node-static

docs/concepts-clients.md, versioned_docs/version-2.10.x/concepts-messaging.md, versioned_docs/version-2.11.x/concepts-messaging.md, versioned_docs/version-2.2.0/concepts-messaging.md, versioned_docs/version-2.2.1/concepts-messaging.md, versioned_docs/version-2.3.0/concepts-messaging.md, versioned_docs/version-2.3.1/concepts-messaging.md, versioned_docs/version-2.3.2/concepts-messaging.md, versioned_docs/version-2.4.0/concepts-messaging.md, versioned_docs/version-2.4.1/concepts-messaging.md, versioned_docs/version-2.4.2/concepts-messaging.md, versioned_docs/version-2.5.0/concepts-messaging.md, versioned_docs/version-2.5.1/concepts-messaging.md, versioned_docs/version-2.5.2/concepts-messaging.md, versioned_docs/version-2.6.0/concepts-messaging.md, versioned_docs/version-2.6.1/concepts-messaging.md, versioned_docs/version-2.6.2/concepts-messaging.md, versioned_docs/version-2.6.3/concepts-messaging.md, versioned_docs/version-2.6.4/concepts-messaging.md, versioned_docs/version-2.7.0/concepts-messaging.md, versioned_docs/version-2.7.1/concepts-messaging.md, versioned_docs/version-2.7.2/concepts-messaging.md, versioned_docs/version-2.7.3/concepts-messaging.md, versioned_docs/version-2.7.4/concepts-messaging.md, versioned_docs/version-2.7.5/concepts-messaging.md, versioned_docs/version-2.8.x/concepts-messaging.md, versioned_docs/version-2.9.x/concepts-messaging.md
This closes https://github.com/apache/pulsar/issues/20097.
=> [fix][doc] MesssageListener inject link

docs/cookbooks-retention-expiry.md, versioned_docs/version-2.10.x/cookbooks-retention-expiry.md, versioned_docs/version-2.11.x/cookbooks-retention-expiry.md, versioned_docs/version-2.2.0/cookbooks-retention-expiry.md, versioned_docs/version-2.2.1/cookbooks-retention-expiry.md, versioned_docs/version-2.3.1/cookbooks-retention-expiry.md, versioned_docs/version-2.3.2/cookbooks-retention-expiry.md, versioned_docs/version-2.4.0/cookbooks-retention-expiry.md, versioned_docs/version-2.4.1/cookbooks-retention-expiry.md, versioned_docs/version-2.4.2/cookbooks-retention-expiry.md, versioned_docs/version-2.5.1/cookbooks-retention-expiry.md, versioned_docs/version-2.5.2/cookbooks-retention-expiry.md, versioned_docs/version-2.7.0/cookbooks-retention-expiry.md, versioned_docs/version-2.7.1/cookbooks-retention-expiry.md, versioned_docs/version-2.7.2/cookbooks-retention-expiry.md, versioned_docs/version-2.7.3/cookbooks-retention-expiry.md, versioned_docs/version-2.7.4/cookbooks-retention-expiry.md, versioned_docs/version-2.7.5/cookbooks-retention-expiry.md, versioned_docs/version-2.8.x/cookbooks-retention-expiry.md, versioned_docs/version-2.9.x/cookbooks-retention-expiry.md
=> [improve][doc] Optimize message retention detail explanation

package.json, tools/pytools/lib/execute/config_doc_generator.py, tools/pytools/lib/execute/pulsar_admin_clidoc_generator.py, tools/pytools/lib/execute/pulsar_clidoc_generator.py, tools/pytools/lib/execute/pulsar_client_clidoc_generator.py, tools/pytools/lib/execute/pulsar_perf_clidoc_generator.py, yarn.lock
This closes https://github.com/apache/pulsar/issues/20214.
=> [fix] Create parents on references generating 

release-notes/versioned/pulsar-3.0.0.md
=> Add PIP 193 to 3.0 release note

blog/2023-04-19-Apache-Pulsar-2-10-4.md, data/release-pulsar.js
[Google doc](https://docs.google.com/document/d/1RgmfoC6lbQjm7wrX_neKr3lw_-5ICHVW5UM1LKmy5Yk/edit#)
=> Release blog 2.10.4

README.md
=> Add How To Contribute section on README

.github/PULL_REQUEST_TEMPLATE.md
=> [improve][misc] add reminder to PR template

docs/security-encryption.md, versioned_docs/version-2.11.x/security-encryption.md, versioned_docs/version-3.0.x/security-encryption.md
Fix some typos in End-to-End Encryption
=> [fix] Fix some typos in End-to-End Encryption

data/events.ts, docusaurus.config.js, src/components/pages/EventsPage/FeaturedEvent/FeaturedEvent.tsx
- Removed the announcement bar.
- Added Pulsar Summit Europe 2023 to the events list.
- Changed Featured Event block text.
=> After Pulsar Virtual Summit Europe 2023

src/components/pages/HomePage/ShortInfo/ShortInfo.tsx
This PR fixes https://github.com/apache/pulsar/issues/20471
=> [improve] homepage button redirects to latest stable version

data/release-python.js, release-notes/versioned/client-python-3.2.0.md
=> Add the release note for Python client 3.2.0

versioned_docs/version-3.0.x/admin-api-namespaces.md
This PR removes extra value from namespace example.
=> [fix][doc] update namespace name in Get replication cluster CLI example.

docusaurus.config.js
https://github.com/apache/pulsar-site/pull/586#issuecomment-1583969934
Before:
After:
=> Move /books page under Learn dropwdown menu

versioned_docs/version-2.9.x/performance-pulsar-perf.md
=> Update performance-pulsar-perf.md - spelling error

docs/io-cdc-debezium.md, docs/io-debezium-source.md, src/components/pages/HomePage/Features/featuresList.ts, versioned_docs/version-2.10.x/io-cdc-debezium.md, versioned_docs/version-2.10.x/io-debezium-source.md, versioned_docs/version-2.11.x/io-cdc-debezium.md, versioned_docs/version-2.11.x/io-debezium-source.md, versioned_docs/version-2.8.x/io-cdc-debezium.md, versioned_docs/version-2.8.x/io-debezium-source.md, versioned_docs/version-2.9.x/io-cdc-debezium.md, versioned_docs/version-2.9.x/io-debezium-source.md, versioned_docs/version-3.0.x/io-cdc-debezium.md, versioned_docs/version-3.0.x/io-debezium-source.md
This PR fixes https://github.com/apache/pulsar/issues/20501
Preview looks good:
=> [doc][improve] add usage notes for Debezium connector

docs/concepts-messaging.md, versioned_docs/version-2.10.x/concepts-messaging.md, versioned_docs/version-2.11.x/concepts-messaging.md, versioned_docs/version-2.2.0/concepts-messaging.md, versioned_docs/version-2.2.1/concepts-messaging.md, versioned_docs/version-2.3.0/concepts-messaging.md, versioned_docs/version-2.3.1/concepts-messaging.md, versioned_docs/version-2.3.2/concepts-messaging.md, versioned_docs/version-2.4.0/concepts-messaging.md, versioned_docs/version-2.4.1/concepts-messaging.md, versioned_docs/version-2.4.2/concepts-messaging.md, versioned_docs/version-2.5.0/concepts-messaging.md, versioned_docs/version-2.5.1/concepts-messaging.md, versioned_docs/version-2.5.2/concepts-messaging.md, versioned_docs/version-2.6.0/concepts-messaging.md, versioned_docs/version-2.6.1/concepts-messaging.md, versioned_docs/version-2.6.2/concepts-messaging.md, versioned_docs/version-2.6.3/concepts-messaging.md, versioned_docs/version-2.6.4/concepts-messaging.md, versioned_docs/version-2.7.0/concepts-messaging.md, versioned_docs/version-2.7.1/concepts-messaging.md, versioned_docs/version-2.7.2/concepts-messaging.md, versioned_docs/version-2.7.3/concepts-messaging.md, versioned_docs/version-2.7.4/concepts-messaging.md, versioned_docs/version-2.7.5/concepts-messaging.md, versioned_docs/version-2.8.x/concepts-messaging.md, versioned_docs/version-2.9.x/concepts-messaging.md, versioned_docs/version-3.0.x/concepts-messaging.md
This closes https://github.com/apache/pulsar/issues/20036.
=> [fix][doc] Drop color code

data/events.ts, docusaurus.config.js, src/components/pages/EventsPage/FeaturedEvent/FeaturedEvent.tsx
- Added link and text to the announcement bar.
- Added link and text to the "Featured Event" section on the `/events` page.
- Updated link to Pulsar Summit Europe 2023 materials at the `/events` page.
---
Live demo: https://pulsar-site-git-pulsar-summit-north-america-2023-teal-tools.vercel.app/
=> Add info about Pulsar Summit North America 2023

docs/developers-landing.md
=> fix: link to contrib guide

docs/administration-geo.md, versioned_docs/version-2.10.x/administration-geo.md, versioned_docs/version-2.11.x/administration-geo.md, versioned_docs/version-2.2.0/administration-geo.md, versioned_docs/version-2.2.1/administration-geo.md, versioned_docs/version-2.3.0/administration-geo.md, versioned_docs/version-2.3.1/administration-geo.md, versioned_docs/version-3.0.x/administration-geo.md
Fix wrong command of create cluster
=> [fix] [doc] fix wrong command of create cluster

.editorconfig, tools/pytools/lib/execute/config_doc_generator.py
=> [fix] Catch up matser docs change update

docs/schema-get-started.md, versioned_docs/version-2.11.x/schema-get-started.md, versioned_docs/version-3.0.x/schema-get-started.md
This PR fixes documentation typo.
=> [fix][doc] fix pulsar consumer name typo 

docs/reference-metrics.md
This PR adds docs for https://github.com/apache/pulsar/pull/20472
=> [improve][doc] add a new metric (pulsar_topic_load_times)

data/resources.ts, docusaurus.config.js, src/components/pages/ResourcesPage/ResourcesPage.tsx, src/pages/resources.tsx
=> [misc] Multiple improvements on Learn page

data/release-node.js, release-notes/versioned/pulsar-client-node-1.9.0.md
=> Add the release note for Nodejs client 1.9.0

src/components/pages/HomePage/ShortInfo/ShortInfo.tsx
Java, Go, Python, C++, Node.js, and C# is 6
=> Fix number of languages in home page

docs/administration-geo.md, versioned_docs/version-2.10.x/administration-geo.md, versioned_docs/version-2.11.x/administration-geo.md, versioned_docs/version-2.2.0/administration-geo.md, versioned_docs/version-2.2.1/administration-geo.md, versioned_docs/version-2.3.0/administration-geo.md, versioned_docs/version-2.3.1/administration-geo.md, versioned_docs/version-2.3.2/administration-geo.md, versioned_docs/version-2.4.0/administration-geo.md, versioned_docs/version-2.4.1/administration-geo.md, versioned_docs/version-2.4.2/administration-geo.md, versioned_docs/version-2.5.0/administration-geo.md, versioned_docs/version-2.5.1/administration-geo.md, versioned_docs/version-2.5.2/administration-geo.md, versioned_docs/version-2.6.0/administration-geo.md, versioned_docs/version-2.6.1/administration-geo.md, versioned_docs/version-2.6.2/administration-geo.md, versioned_docs/version-2.6.3/administration-geo.md, versioned_docs/version-2.6.4/administration-geo.md, versioned_docs/version-2.7.0/administration-geo.md, versioned_docs/version-2.7.1/administration-geo.md, versioned_docs/version-2.7.2/administration-geo.md, versioned_docs/version-2.7.3/administration-geo.md, versioned_docs/version-2.7.4/administration-geo.md, versioned_docs/version-2.7.5/administration-geo.md, versioned_docs/version-2.8.x/administration-geo.md, versioned_docs/version-2.9.x/administration-geo.md, versioned_docs/version-3.0.x/administration-geo.md
This PR Closes apache/pulsar#20742
=> [doc][feat] use replicationClusters instead of setReplicationClusters

contribute/setup-building.md
This PR fixes wording on the setup and building page
=> [fix][docs] Fix wording in setup and building page

data/release-cpp.js, release-notes/versioned/client-cpp-3.3.0.md
=> Add the release note for C++ client 3.3.0

src/pages/download.mdx
This closes https://github.com/apache/pulsar/issues/20964.
=> [improve] Downloads page anchors

docusaurus.config.js
This PR updates the banner to promote Pulsar Summit 2023
=> [improve][website] update banner to promote Pulsar Summit 2023

tools/pytools/poetry.lock
=> build(deps): Upgrade pytools deps

docs/io-cdc-debezium.md, docs/io-debezium-source.md, versioned_docs/version-2.11.x/io-cdc-debezium.md, versioned_docs/version-2.11.x/io-debezium-source.md, versioned_docs/version-3.0.x/io-cdc-debezium.md, versioned_docs/version-3.0.x/io-debezium-source.md, versioned_docs/version-3.1.x/io-cdc-debezium.md, versioned_docs/version-3.1.x/io-debezium-source.md
* This closes #536.
* This closes #685.
=> Fix io cdc debezium

docs/develop-load-manager.md
=> [fix][doc] Correct ExtensibleLoadManagerImpl class name

data/release-python.js, release-notes/versioned/client-python-3.3.0.md
=> Add the release note for Python client 3.3.0

blog/2023-06-28-pulsar-summit-north-america-2023-cfp.md, blog/2023-08-28-pulsar-sessions-in-communityovercode-aisa-2023.md
The vedio and slices are not avaiable for now. We can update them later or wait one more week for slices and one more month for vedio.
=> Add a recap for Apache Pulsar Sessions in CommunityOverCode Asia 2023

docs/admin-api-brokers.md, docs/admin-api-clusters.md, docs/admin-api-features.md, docs/admin-api-functions.md, docs/admin-api-namespaces.md, docs/admin-api-overview.md, docs/admin-api-packages.md, docs/admin-api-permissions.md, docs/admin-api-schemas.md, docs/admin-api-tenants.md, docs/admin-api-tools.md, docs/admin-api-topics.md, docs/admin-api-transactions.md, docs/admin-api-tutorial.md, docs/admin-api-use-cases.md, docs/admin-get-started.md, docs/reference-terminology.md
=> [improve][doc] SEO for Admin API

docs/pulsar-api-overview.md, docs/reference-cli-tools.md, docs/reference-rest-api-overview.md, docs/reference-terminology.md
=> [improve][doc] SEO for Reference

docs/client-libraries-clients.md, docs/client-libraries-cluster-level-failover.md, docs/client-libraries-consumers.md, docs/client-libraries-cpp-initialize.md, docs/client-libraries-cpp-setup.md, docs/client-libraries-cpp-use.md, docs/client-libraries-dotnet-initialize.md, docs/client-libraries-dotnet-setup.md, docs/client-libraries-dotnet-use.md, docs/client-libraries-go-initialize.md, docs/client-libraries-go-setup.md, docs/client-libraries-go-use.md, docs/client-libraries-java-initialize.md, docs/client-libraries-java-setup.md, docs/client-libraries-java-use.md, docs/client-libraries-node-configs.md, docs/client-libraries-node-initialize.md, docs/client-libraries-node-setup.md, docs/client-libraries-node-use.md, docs/client-libraries-producers.md, docs/client-libraries-python-initialize.md, docs/client-libraries-python-setup.md, docs/client-libraries-python-use.md, docs/client-libraries-readers.md, docs/client-libraries-rest.md, docs/client-libraries-schema.md, docs/client-libraries-tableviews.md, docs/client-libraries-websocket.md, docs/client-libraries.md
This PR do SEO for Client Libraries.
=> [improve][doc] SEO for Client Libraries

blog/2023-10-10-announcing-apache-pulsar-3-1.md
=> Post 3.1 announcement blog

docs/tiered-storage-filesystem.md, docs/tiered-storage-s3.md, versioned_docs/version-2.11.x/tiered-storage-filesystem.md, versioned_docs/version-2.11.x/tiered-storage-s3.md, versioned_docs/version-3.0.x/tiered-storage-filesystem.md, versioned_docs/version-3.0.x/tiered-storage-s3.md, versioned_docs/version-3.1.x/tiered-storage-filesystem.md, versioned_docs/version-3.1.x/tiered-storage-s3.md
This PR fix doc for tiered-storage-filesystem NFS TabItem.
https://pulsar.apache.org/docs/3.1.x/tiered-storage-filesystem/. 
=> Fix tiered-storage-filesystem NFS TabItem

docs/security-authorization.md, docs/security-tls-authentication.md, docs/security-tls-transport.md
=> Refine SSL/TLS related documents

docusaurus.config.js
This PR fixes https://github.com/apache/pulsar/issues/21478
=> [feat] add social card for render

docusaurus.config.js, src/components/pages/EventsPage/FeaturedEvent/FeaturedEvent.tsx
=> misc: remove banner after the pulsar summit

data/release-cpp.js, release-notes/versioned/client-cpp-3.4.0.md
=> Add the release note for C++ client 3.4.0

src/components/pages/CommunityPage/sections/discussions/DiscussionPlatforms.tsx
This PR references Linen to browse and search the Slack discussions history and make it searchable with Google or other search engines.
=> [doc][community page] add Linen to the Discussions section of the Community page

contribute/release-process.md
Fix https://github.com/apache/pulsar/issues/20438
=> [fix][site] Update docker image staging command

contribute/release-process.md
=> Fix KEYS file address for release process docs.

docs/concepts-messaging.md
This PR adds doc for https://github.com/apache/pulsar/pull/21589
=> [improve][doc] Doducment dlq producerName

docs/concepts-broker-load-balancing-concepts.md
Tiny typo in the docs adding a missing space.
=> [fix][doc] Add missing space in sentence

contribute/setup-building.md
=> Specify Maven wrapper in setup-building.md

data/release-cpp.js, release-notes/versioned/client-cpp-3.4.2.md
=> Add the release note for C++ client 3.4.2

src/components/downloads.tsx
See https://infra.apache.org/release-download-pages.html#download-page.
=> [improve][misc] Comply with INFRA download policies

blog/2024-01-12-pulsar-2023-year-in-review.md
This PR adds a blog post for the 2023 review.
=> [blog] 2023 year in review

docs/client-libraries-consumers.md
=> [fix][doc] Fix a link anchor

docs/concepts-messaging.md
This PR fixes https://github.com/apache/pulsar/pull/21890
=> [fix][doc] Fix DLQ producer name

contribute/setup-building.md
This PR adds doc for #[21750](https://github.com/apache/pulsar/issues/21750)
This PR fixes #[21750](https://github.com/apache/pulsar/issues/21750)
=> [doc] running pulsar server on windows doesn't supported yet is added

static/charts/index.yaml
Adding Pulsar Helm Chart 3.2.0 to index.yaml. Vote email thread: https://lists.apache.org/thread/6wst9jqg0w9otyn4ltwoq574029czoqy
=> Adding Pulsar Helm Chart 3.2.0 to index.yaml

data/release-node.js, release-notes/versioned/pulsar-client-node-1.10.0.md
=> Add the release note for Nodejs client 1.10.0

data/events.ts, src/components/pages/EventsPage/Cards/Cards.tsx
This PR add summit events 2024 display
=> [feat] add summit events 2024 display

docs/getting-started-docker.md, versioned_docs/version-3.2.x/getting-started-docker.md
This PR fixes https://github.com/apache/pulsar/issues/22027
=> Fix missing docker cmd

static/reference/index.html
Fixes https://github.com/apache/pulsar/issues/22046
=> Add 3.2.x to reference index

blog/2024-02-12-announcing-apache-pulsar-3-2.md
This PR adds a blog post for 3.2.0 release announcement and main features highlight
=> [blog] 3.2.0 release announcement blog post

contribute/release-policy.md
This PR adds doc for https://lists.apache.org/thread/objr5q14l4769pj6131fnf6y8vmnznbl
=> [improve][doc] Clarify version upgrading from 3.0 to 3.x is ok

blog/2024-02-12-announcing-apache-pulsar-3-2.md
This PR fixes incorrect information on compatibility between releases on Pulsar 3.2 blog post
=> [fix][blog] fix incorrect information on compatibility between releases on Pulsar 3.2 blog post

docs/io-azuredataexplorer-sink.md, docs/io-connectors.md
This PR adds doc for https://github.com/apache/pulsar/pull/22006
=>  Documentation added for Azure data explorer IO-sink

docusaurus.config.js
=> Call for speakers - Pulsar Summit EU 2024

src/theme/DocVersionBanner/index.js
=> Fix - recommended version banner shows same version two times

docs/txn-use.md, versioned_docs/version-3.0.x/txn-use.md, versioned_docs/version-3.1.x/txn-use.md, versioned_docs/version-3.2.x/txn-use.md
=> The sample code of transaction is missing ".build();"

src/components/ui/ArticleThumb/ArticleThumb.module.css, src/css/typography.css
- Slightly reduce font line-height in docs for better readability.
- Changed "Suggest changes" and "Get support" links color to black
=> Minor style changes

docs/admin-api-schemas.md, docs/txn-use.md, versioned_docs/version-2.11.x/admin-api-schemas.md, versioned_docs/version-3.0.x/admin-api-schemas.md, versioned_docs/version-3.1.x/admin-api-schemas.md, versioned_docs/version-3.2.x/admin-api-schemas.md
=> The sample code of schema has a expressing error

data/release-pulsar.js
=> Fix version issue

release-notes/versioned/pulsar-3.2.0.md, release-notes/versioned/pulsar-3.2.1.md
Fix the doc, not list by alphabetic
=> Fix doc issue

docusaurus.config.js
https://registration.socio.events/e/pulsarvirtualsummiteurope2024
=> Summit EU 2024 announcement bar

src/components/pages/CommunityPage/CommunityPage.tsx, src/components/pages/CommunityPage/sections/discussions/DiscussionPlatforms.tsx, src/pages/contact.mdx
* update contact page since it was outdated
* improve instructions for subscribing to mailing lists
* add comments about security vulnerability issue reporting
=> Update contact, improve mailing list subscribe, add comment about security issues

docs/about.md, versioned_docs/version-3.0.x/about.md, versioned_docs/version-3.2.x/about.md
- Update the outdated "Join the community" section on the about page in docs
=> Update the outdated "Join the community" section on the about page in docs

src/pages/download.mdx
Ref: https://github.com/apache/pulsar/issues/22276
=> Add DockerHub repo link to downloads page

data/case-studies.ts
=> Fix Cisco case study which seemed like it was a copy of a presentation description

src/components/pages/CommunityPage/CommunityPage.module.css, src/components/pages/CommunityPage/CommunityPage.tsx
Removed the "Show more" button for the desktop screen size. 
It's not much to scroll.
https://github.com/apache/pulsar-site/assets/9302460/53339e23-1de7-412b-8f18-8d6e1a8953ea
=> Always show all committers on community page

src/components/pages/CommunityPage/CommunityPage.module.css
=> Fix avatar aspect ratio on tablet screen size

data/release-cpp.js, release-notes/versioned/client-cpp-3.5.1.md
=> Add the release note for C++ client 3.5.1

data/release-node.js, release-notes/versioned/pulsar-client-node-1.11.0.md
=> Add the release note for Nodejs client 1.11.0

data/release-python.js, release-notes/versioned/client-python-3.5.0.md
=> Add the release note for Python client 3.5.0

docs/deploy-docker.md, versioned_docs/version-3.0.x/deploy-docker.md, versioned_docs/version-3.1.x/deploy-docker.md, versioned_docs/version-3.2.x/deploy-docker.md
=> I want break line in the command

docs/admin-api-topics.md, versioned_docs/version-2.10.x/admin-api-topics.md, versioned_docs/version-2.11.x/admin-api-topics.md, versioned_docs/version-3.0.x/admin-api-topics.md, versioned_docs/version-3.1.x/admin-api-topics.md, versioned_docs/version-3.2.x/admin-api-topics.md
=> Fix wrong Java API call to delete partitioned topics

docs/txn-advanced-features.md
This reverts commit b7ada2f9207297087b614f18dcac8b0676eb39bd.
It was mistakenly merged in #712
=> Revert "[improve][doc]Add introduction of transaction isolation level in the txn-advanced-features.md (#712)"

docs/develop-load-manager.md
=> Remove unnecessary characters

docs/administration-geo.md, versioned_docs/version-3.0.x/administration-geo.md, versioned_docs/version-3.1.x/administration-geo.md, versioned_docs/version-3.2.x/administration-geo.md
Add information to unload the topic when you execute an earliest replication
As mentioned in motivation of
[PIP-356](https://github.com/apache/pulsar/blob/master/pip/pip-356.md#motivation)
=> Solves apache/pulsar/issues/22848

contribute/release-process.md, contribute/setup-building.md, contribute/setup-git.md, docusaurus.config.js, preview.sh, sidebarsDevelopment.js
Renamed setup-mergetool.md to setup-git.md and added more git tips.
=> Rename setup-mergetool.md to setup-git.md and add more git tips

docs/reference-metrics-opentelemetry.md
=> [feat][broker] PIP-264: Add schema registry metrics

data/matrix.js, docs/txn-use.md, versioned_docs/version-3.0.x/txn-use.md, versioned_docs/version-3.1.x/txn-use.md, versioned_docs/version-3.2.x/txn-use.md, versioned_docs/version-3.3.x/txn-use.md
https://github.com/apache/pulsar/issues/22928
=> add golang and .NET in transaction support list

docs/reference-metrics-opentelemetry.md
=> [feat][doc] PIP-264: Add OpenTelemetry metadata store metrics reference

docs/reference-metrics-opentelemetry.md
=> [feat][doc] PIP-264: Add broker connection metrics

docs/reference-metrics-opentelemetry.md
=> [feat][doc] PIP-264: Add managed ledger metrics reference

docs/administration-geo.md, versioned_docs/version-2.11.x/administration-geo.md, versioned_docs/version-3.0.x/administration-geo.md, versioned_docs/version-3.2.x/administration-geo.md, versioned_docs/version-3.3.x/administration-geo.md
Tries to clarify a possible increase in backlog and from where it is coming
Solves apache/pulsar/issues/22926
=> Add a note about increases in backlog when replicated subscription is activated

data/release-node.js, release-notes/versioned/pulsar-client-node-1.11.1.md
=> Add the release note for Nodejs client 1.11.1

docs/reference-metrics-opentelemetry.md
=> [feat][doc] PIP-264: Add OpenTelemetry HTTP rate limiting metrics reference

docs/txn-use.md, versioned_docs/version-3.0.x/txn-use.md, versioned_docs/version-3.1.x/txn-use.md, versioned_docs/version-3.2.x/txn-use.md, versioned_docs/version-3.3.x/txn-use.md
The code block format is broken:
=> [fix][doc] Fix code block format for transaction demo

data/release-cpp.js, release-notes/versioned/client-cpp-3.6.0.md
=> Add release note for cpp 3.6.0

versioned_docs/version-3.3.x/getting-started-helm.md
=> docs: rename helm repo 'apache' to 'pulsar'

docs/getting-started-docker-compose.md, versioned_docs/version-4.0.x/getting-started-docker-compose.md
=> Update typo in getting-started-docker-compose.md

data/release-node.js, release-notes/versioned/pulsar-client-node-1.13.0.md
=> Add the release note for Nodejs client 1.13.0

data/release-python.js, release-notes/versioned/client-python-3.6.1.md
=> Add release note for Python client 3.6.1

data/release-node.js, release-notes/versioned/pulsar-client-node-1.13.1.md
=> Add the release note for Nodejs client 1.13.1

docs/concepts-messaging.md, versioned_docs/version-4.0.x/concepts-messaging.md
Update doc for https://github.com/apache/pulsar/pull/24020.
=> [feat] [doc] PIP-409: support producer configuration for retry/dead letter topic producer

data/resources.ts, src/components/pages/ResourcesPage/Cards/Cards.tsx
This PR adds a new article titled "Goodbye Distributed Locks: Message Orchestration at Scale with Apache Pulsar" to the resources under the articles category. The article, published on the Attentive Tech Blog in April 2025, discusses architectural evolution's for achieving mutual exclusivity at scale using Apache Pulsar.
| Title                                                                 | Published    | Forum           | Tags                                              | Link                                                                                   |
|----------------------------------------------------------------------|--------------|------------------|---------------------------------------------------|----------------------------------------------------------------------- …
=> Update articles page with Attentive blog post

data/release-cpp.js, release-notes/versioned/client-cpp-3.7.1.md
=> Add C++ Client release note 3.7.1

data/release-python.js, release-notes/versioned/client-python-3.7.0.md
=> Add release note for python client 3.7.0

data/release-node.js, release-notes/versioned/pulsar-client-node-1.14.0.md
=> Add the release note for node.js client 1.14.0

data/release-cpp.js, release-notes/versioned/client-cpp-3.7.2.md
=> Add C++ Client release note 3.7.2

docs/io-use.md, versioned_docs/version-3.2.x/io-use.md, versioned_docs/version-3.3.x/io-use.md, versioned_docs/version-4.0.x/io-use.md
=> Fix links in "How to use Pulsar connectors" page

package.json, src/components/pages/BooksPage/BooksPage.tsx, src/css/announcement-bar.css, src/css/docs.css, src/css/navbar.css, src/css/typography.css, src/types/global.d.ts, src/types/theme.d.ts, yarn.lock
=> Upgrade to Docusaurus 3.8.1

blog/2025-09-09-announcing-apache-pulsar-4-1.md, docusaurus.config.ts, src/css/blog.css
=> Added Announcment Blog for 4.1 Release
